(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"index_atlas_NP_", frames: [[322,203,124,156],[322,0,183,201],[322,361,98,99],[0,0,320,480]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.nineteenbottomleft = function() {
	this.spriteSheet = ss["index_atlas_NP_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.nineteencheese = function() {
	this.initialize(img.nineteencheese);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,198,102);


(lib.nineteentomatoes = function() {
	this.spriteSheet = ss["index_atlas_NP_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.nineteentopright = function() {
	this.spriteSheet = ss["index_atlas_NP_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.seventeentable = function() {
	this.spriteSheet = ss["index_atlas_NP_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.whiterectanglefadeone = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgaKAmmMAAAhNLMA0VAAAMAAABNLg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.whiterectanglefadeone, new cjs.Rectangle(-167.4,-246.9,335,494), null);


(lib.smallbites = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("Ag7BFQgagaAAgoQAAgqAbgcQAbgcAoAAQAkABAUAUQAVAUAAAiQAAAMgDADQgEAEgNAAIhGAAQgGAAgDgEQgDgDAAgEQAAgFADgCQADgDAGAAIAmAAIAJgCQACgBAAgEQAAgSgMgMQgMgMgQAAQgWAAgKATQgLATAAAbQAAAcAPAVQAOAUAXAAQANABAKgDQAJgEAJgFIAGgGQAKgIAFAAQAEAAACAEQADACAAADQAAAFgFAGQgEAHgIAGQgQANgPAGQgOAGgSAAQgmAAgagbg");
	this.shape.setTransform(122.9,42.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("Ag3BbQgJgDAAgJQAAgFAJgEIAFgBQAEgEADgFQACgHAAgNIAAgNIgBgOIAAgMQAAghgBgJQgCgKgEgDIgIgDQgLgDAAgHQAAgEADgDQADgEAIgDIAZgIIAQgDQAKAAACAZIABADIABABQAJgOALgIQAKgIAKAAQAMAAAIAIQAIAIAAANQAAAMgGAHQgGAIgKAAIgJgCIgIgGIgFgHQgBgEgCAAQgNAAgFARQgEASAAA2QAAAQACAJQACAHAEADIAHACQALADAAAIQAAAHgKADQgKADgYAAQgcAAgJgDg");
	this.shape_1.setTransform(106.7,42.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AhCBFQgagbAAgpQAAgpAcgbQAbgcAoAAQAnAAAZAaQAaAaAAAoQAAAqgbAcQgbAdgnAAQgoAAgagbgAgig1QgLAOAAAYQAAAkAPAYQAPAZAWAAQARAAAMgPQALgQAAgYQAAgjgQgYQgQgYgUgBQgSABgLAPg");
	this.shape_2.setTransform(89,42.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("ABFCBQgLgDAAgIQAAgIAMgEIAIgEQADgDABgIQACgIAAgYIAAgKIgBhNIAAguIgXA8Qg2CMgMAAQgFAAgLgTQgKgTgag8IgohcIgCBIIAAAxIABAiQABAJADACIAIAEQALAEAAAIQAAAHgJAEQgKADgWAAQgUAAgJgEQgJgDAAgIQAAgGAKgFQAKgFABgDQACgJADgvQADguAAg6IAAgGQAAgTgCgHQgBgGgFgDIgIgEQgMgEAAgIQAAgHAIgCQAJgDAaAAIAaAAIAIACQADACANAhIAKAaIAGANQAsBtADAAQAEAAAQgnQARgmAWhBIAEgLQAHgUAFgGQADgEAHgBIAZgBQAZAAAIADQAIACAAAHQAAAIgKAEIgFACQgGADgBAHQgCAHAAAdIACBnQABAvACAHQABAEAIADIAEACIAHAEQACADAAAEQAAAIgKADQgKADgeAAQgcAAgJgDg");
	this.shape_3.setTransform(62.1,38.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AhuBvQgigaAAgrQAAgXALgTQALgRAYgQIABgCQgJgIgDgJQgEgJAAgJQgBgdAWgSQAVgTAhAAQAWAAAQAJQAPAJAAALQAAAEgDADQgEADgFAAIgPgFQgNgEgKAAQgPAAgJAJQgIAKgBAQQAAAHACAFQADAFAFAFQAEAEAIAEIALAEIADABIACADQAAAEgHAIQgHAHgFAAIgJgBIgMgFQgKAJgGAMQgFANAAARQAAAjAXAWQAXAXAjAAQAeAAASgPQASgQAAgYQAAgQgIgJQgHgJgMAAQgNAAgJAHQgHAIAAALIAAAEIAAACIgDABIgCAAQgHAAgEgFQgEgFAAgJQAAgbBQglIAGgCQAVgKAKgLQAMgLAAgNQAAgJgFgEQgFgEgJAAIgHABIgHAAQgFAAgCgCQgCgDAAgEQAAgIAKgFQAKgFAPAAQAUAAALAKQAMALAAATQAAAXgUASQgTATgpAPQAQAGAKAOQAIAOAAASQAAAOgGANQgFANgKAMQgRASgZAJQgZAJggAAQg4AAghgag");
	this.shape_4.setTransform(20.8,38.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AgNBfIgUgDIgFADIgGABIgEgBIgDgCQgGgFgGgPQgFgPAAgOQAAgFADgEQADgEAFAAQAIAAAJAOIAHAMQAFAHAKAEQAJAFAKgBQANAAAHgFQAHgHAAgKQAAgQgegOIgLgGQgcgNgKgMQgKgLAAgSQAAgXAQgPQARgQAaAAIAMABIANACIAJgDIAGgBQAJAAAIAOQAJAOAAARQAAAGgDAEQgDADgFAAQgFAAgEgDQgEgDgFgKQgHgLgHgEQgIgFgKAAQgKAAgGAGQgHAGAAAKQAAAIAHAGQAHAHAWALIACABQAzAYAAAeQAAAagUARQgTARgeAAg");
	this.shape_5.setTransform(-13.7,42.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("Ag3BbQgJgDAAgJQAAgFAJgEIAFgBQAEgEACgFQACgHABgNIAAgNIgBgOIAAgMQAAghgCgJQgBgKgDgDIgJgDQgLgDAAgHQAAgEADgDQAEgEAHgDIAZgIIARgDQAIAAADAZIABADIAAABQAKgOALgIQAKgIAKAAQAMAAAIAIQAIAIAAANQAAAMgGAHQgGAIgKAAIgKgCIgHgGIgFgHQgBgEgCAAQgNAAgFARQgEASAAA2QAAAQABAJQADAHAEADIAHACQAMADgBAIQABAHgLADQgKADgYAAQgcAAgJgDg");
	this.shape_6.setTransform(-28.1,42.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("Ag7BFQgagaAAgoQAAgqAbgcQAbgcAoAAQAkABAUAUQAVAUAAAiQAAAMgDADQgEAEgNAAIhGAAQgGAAgDgEQgDgDAAgEQAAgFADgCQADgDAGAAIAmAAIAJgCQACgBAAgEQAAgSgMgMQgMgMgQAAQgWAAgKATQgLATAAAbQAAAcAPAVQAOAUAXAAQANABAKgDQAJgEAJgFIAGgGQAKgIAFAAQAEAAACAEQADACAAADQAAAFgFAGQgEAHgIAGQgQANgPAGQgOAGgSAAQgmAAgagbg");
	this.shape_7.setTransform(-45.2,42.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("AgJBuQgJgDgGgGQgHgGgDgKQgCgKAAgbIAAhhIgRAAIgFgCIgCgFIAAgEQAAgHATgQIAIgGIAHgGQATgRAHAAIAFABQAAABABAAQAAABAAAAQAAABABABQAAAAAAABIAAAiIApAAQAEAAACACQACACAAAFIAAAFQAAAEgCACQgCACgEABIgmAAIgDABIgBAEIAABaQAAAXAEAHQAEAFALABQAFgBAKgDIAMgCQAEgBADADQACADAAAEQAAAKgPAJQgQAJgTAAQgLAAgJgDg");
	this.shape_8.setTransform(-61.2,41);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E46").s().p("AgJBuQgJgDgGgGQgHgGgDgKQgCgKAAgbIAAhhIgRAAIgFgCIgCgFIAAgEQAAgHATgQIAIgGIAHgGQATgRAHAAIAFABQAAABABAAQAAABAAAAQAAABABABQAAAAAAABIAAAiIApAAQAEAAACACQACACAAAFIAAAFQAAAEgCACQgCACgEABIgmAAIgDABIgBAEIAABaQAAAXAEAHQAEAFALABQAFgBAKgDIAMgCQAEgBADADQACADAAAEQAAAKgPAJQgQAJgTAAQgLAAgJgDg");
	this.shape_9.setTransform(-74.2,41);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E46").s().p("AAhBWIgKgJIgIAEQgWAPgWAAQgbAAgRgQQgRgPAAgaQAAgdAWgPQAVgRAmAAQAJAAAFADQAFADgBAHQAAAKgMAAQgSAAgLAIQgLAJAAAQQAAAOAJAJQAKAJAQAAQASAAAHgIQAHgIABgTIAAhFQAAgQgIgJQgGgJgMAAQgKAAgHAFQgIADgHAJIgEAEQgLAOgNAAQgGAAgFgEQgFgFABgIQAAgRAVgMQAVgMAhAAQAUAAAPAGQAOAFAIAKQAGAHACAMQADALAAAaIAAA6QAAALABAFQACAFADABIAGABQALAEAAAGQABAIgMAIQgNAHgQAAQgJAAgIgKg");
	this.shape_10.setTransform(-90.3,42.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E46").s().p("AgeCEQgJgDAAgJQAAgGAIgDIAJgFQADgDABgLIACgkIAAgdIgBgiIAAgNQAAgvgBgNQgCgNgEgCIgLgFQgMgDAAgGQAAgFAEgDQAEgDANgEIAYgHIASgDQAGAAACAEQACADAAAJIAAAOQgCBBAABBIABA/QABANADAEIAKAFQAJADAAAIQAAAGgJAEQgJACgYAAQgbAAgJgCg");
	this.shape_11.setTransform(-105.7,38.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E46").s().p("AhfCBQgJgCgBgJQAAgHAMgEIAIgFQADgDACgVQACgWAAg5IgChFQgBgbgCgDQgCgDgKgEQgKgEAAgGQAAgHAGgDQAFgEAMAAIATAAIAVAAIAlgBIAdAAQAoAAAVARQAVASAAAjQAAAmgaAUQgZAUgwAAQgTAAABgNQAAgMAPAAQAXAAAOgNQAOgLAAgcQAAgZgOgMQgPgLgcAAQgOAAgFACQgGACgBAFIgCARIgCAmIAABQIACA0QABANADADIAIAEQAMAEgBAHQABAJgLACQgKAEgcAAQgdAAgLgEg");
	this.shape_12.setTransform(-121,38.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E46").s().p("AgUA4QgDgCAAgCIAEgIIAEgFIAKgUQAEgJAAgEIgBgFIgGgDQgKgEgEgGQgFgHABgJQgBgNAIgIQAIgIALAAQALAAAIALQAJALAAAQQAAAMgGANQgEANgNAUIgJAOQgDAFgEAAQgFAAgEgCg");
	this.shape_13.setTransform(94.7,12.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E46").s().p("AgNBfIgUgDIgFADIgGABIgEgBIgDgCQgGgFgGgPQgFgPAAgOQAAgFADgEQADgEAFAAQAIAAAJAPIAHALQAFAHAKAEQAJAFAKAAQANgBAHgFQAHgHAAgKQAAgQgegOIgLgGQgcgOgKgLQgKgLAAgSQAAgXAQgPQARgQAaAAIAMABIANACIAJgDIAGgBQAJAAAIAOQAJAPAAAQQAAAGgDAEQgDADgFAAQgFAAgEgDQgEgEgFgIQgHgMgHgEQgIgFgKAAQgKAAgGAGQgHAGAAAKQAAAIAHAGQAHAHAWALIACABQAzAYAAAfQAAAZgUARQgTARgeAAg");
	this.shape_14.setTransform(81.2,3.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E46").s().p("Ag7BFQgagbAAgnQAAgqAbgbQAbgdAoAAQAkABAUAUQAVAUAAAiQAAAMgDADQgEADgNABIhGAAQgGAAgDgEQgDgDAAgEQAAgFADgCQADgDAGAAIAmAAIAJgCQACgBAAgEQAAgSgMgMQgMgMgQAAQgWAAgKATQgLATAAAbQAAAcAPAVQAOAUAXAAQANAAAKgCQAJgDAJgGIAGgGQAKgIAFAAQAEAAACAEQADACAAADQAAAFgFAHQgEAGgIAGQgQANgPAGQgOAGgSAAQgmAAgagbg");
	this.shape_15.setTransform(63.7,3.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E46").s().p("AgJBuQgJgDgGgGQgHgGgDgKQgCgKAAgbIAAhiIgRAAIgFgBIgCgFIAAgEQAAgGATgRIAIgGIAHgGQATgRAHAAIAFABQAAABABAAQAAABAAAAQAAABABABQAAAAAAABIAAAjIApAAQAEAAACABQACACAAAFIAAAEQAAAFgCACQgCACgEAAIgmAAIgDACIgBAEIAABaQAAAYAEAGQAEAFALABQAFAAAKgEIAMgCQAEAAADACQACADAAADQAAALgPAJQgQAJgTAAQgLAAgJgDg");
	this.shape_16.setTransform(47.7,1.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E46").s().p("AgfCDQgJgDAAgJQAAgGAJgDIAEgCQAFgDACgGQABgGAAgOIAAgMIAAgPIAAgTQABgdgCgHQgCgJgDgCIgJgDQgLgEAAgGQAAgEAEgDQADgEAIgDIAcgJIASgDQAFAAACADQADAEgBAIIAAALIAAAJIgBAtIAAABIgBAtQAAASACAHQABAHAEACIAHADQAJAEAAAHQAAAHgJADQgIADgYAAQgcAAgIgDgAgVhcQgJgGABgKQAAgKAIgHQAJgIAMAAQALAAAIAHQAHAHAAAKQABAKgJAHQgIAHgMAAQgMAAgHgHg");
	this.shape_17.setTransform(35.8,-0.9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006E46").s().p("AgNCEIgkgBIgSAAIgUABQgNAAgGgEQgHgDAAgHQAAgHAKgEQAJgDACgDQADgFABgaIAChHIgChFQgBgagDgEQgCgDgJgEQgKgEAAgGQAAgIAGgCQAFgEALAAIAUAAIAVAAIAlgBIAcAAQAoAAAVAQQAVARAAAeQAAAZgPAQQgPAPgdAFQAlAEATAQQAUATAAAeQAAAigZATQgYATgsAAgAgchqQgGACgBADQgDAFgBARIgBA0IAABNIABAjQABAKADAFQACAEAJACQAJADAPgBQAeAAAQgMQAPgNAAgXQAAgagSgNQgRgMghAAQgQAAAAgKQAAgOAPAAQAYAAAQgLQAPgKAAgZQAAgXgOgMQgPgLgdAAg");
	this.shape_18.setTransform(18,-0.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006E46").s().p("AgeCDQgJgCAAgJQAAgGAIgDIAJgFQADgDABgLIACgkIAAgdIgBghIAAgPQAAgtgBgOQgCgNgEgCIgLgFQgMgDAAgGQAAgEAEgEQAEgDANgEIAYgHIASgDQAGAAACAEQACADAAAJIAAAOQgCBBAABBIABA/QABANADAEIAKAFQAJADAAAIQAAAGgJADQgJADgYAAQgbAAgJgDg");
	this.shape_19.setTransform(-9.9,-1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#006E46").s().p("AgeCDQgJgCAAgJQAAgGAIgDIAJgFQADgDABgLIACgkIAAgdIgBghIAAgPQAAgtgBgOQgCgNgEgCIgLgFQgMgDAAgGQAAgEAEgEQAEgDANgEIAYgHIASgDQAGAAACAEQACADAAAJIAAAOQgCBBAABBIABA/QABANADAEIAKAFQAJADAAAIQAAAGgJADQgJADgYAAQgbAAgJgDg");
	this.shape_20.setTransform(-20.2,-1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#006E46").s().p("AAgBWIgJgJIgIAEQgWAPgXAAQgbAAgQgQQgQgPAAgaQAAgdAVgPQAVgRAnAAQAIAAAFADQAFADAAAHQAAAKgNAAQgSAAgLAIQgLAJAAAQQAAAOAKAJQAJAJARAAQAQAAAIgIQAIgIgBgTIAAhFQAAgQgGgJQgIgJgMAAQgIAAgIAFQgIADgHAJIgEAEQgLAOgMAAQgIAAgEgEQgEgFgBgIQAAgRAWgMQAVgMAhAAQAUAAAOAGQAPAFAJAKQAEAHADAMQACALAAAaIAAA6QABALABAFQACAFAEABIAFABQAMAEAAAGQAAAIgNAIQgMAHgQAAQgIAAgKgKg");
	this.shape_21.setTransform(-34.5,3.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#006E46").s().p("AiUBbQgJgDAAgJQAAgFAJgEIAFgCQAFgDABgFQADgGAAgOIAAgNIgBgOIAAgLQAAgigCgJQgBgLgEgCIgIgDQgLgDAAgHQAAgEADgDIALgGIAbgKIASgDQAFAAADADQACAEAAAGIAAAJIAAADIABACIABAAIABAAIABgBIAEgEIACgCQAWgUAWAAQAJAAAIADQAIADAHAEQAHAFAGAIQAHAJABgBQADABAFgGIAIgIQAMgLAJgDQAJgEAKAAQAWAAAQAJQAPAIAHAQQAJAQgBA1IABASIgBALIAAAIQAAAKACAFQACAFAFACIAFACQAJAEAAAFQAAAJgJACQgIAEgdAAQgagBgJgCQgJgDAAgHQAAgHAKgEIAHgDQAEgCACgJQABgKAAgVQAAg1gGgPQgIgOgTAAQgWAAgJASQgJATAAAsIAAAJQAAAUACAHQACAFAEADIAFACQAJAEAAAFQAAAJgIACQgJAEgcAAQgYgBgJgCQgJgDAAgHQAAgHAJgEIAHgCQAEgCACgIQACgIAAgUQAAg6gIgOQgHgQgUABQgJgBgJAHQgJAFgFAKQgEAIgBAQQgDANAAAjQAAARACAGQACAHAEACIAHACQAJAEAAAHQAAAHgJADQgJADgYAAQgcAAgJgDg");
	this.shape_22.setTransform(-61.4,3.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#006E46").s().p("AgtCEQgUgEgNgIQgHgEgFgPQgFgQAAgVQAAgIADgFQAEgFAGABQAIAAAJAQIAFAHQALAVAOAKQAOAIATABQATAAAOgMQAOgMAAgSQAAgZg2gYIgGgCQgsgSgPgRQgOgQAAgaQAAghAYgVQAYgVAngBIAVADIAZAFIAIgEIAGgCQAEAAAEADQADACAEAHQAGAMAEAMQAEALAAAKQAAAGgDADQgDADgFAAQgKAAgJgMIgDgEQgKgOgMgGQgNgHgPABQgUgBgLAKQgMAKAAAQQAAAPAKAKQAJAKAnAQIAIAEQAgANAPANQAKAJAFANQAGAMAAAOQAAAmgaAUQgbAWgtAAQgXAAgUgFg");
	this.shape_23.setTransform(-88.7,-0.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#006E46").s().p("AhUB5QgJgIAAgLQAAgJAHgHQAGgGAKgBIAIABIAFAFIAFAGQAFAIADAAQAKAAAJgNQAKgOgBgOQABgQgNgdIgCgFIgeg/IgQgkQgDgGgLgEIAAgBQgGgCgCgDQgDgDAAgDQAAgIAKgEQAJgDAbAAQAbAAAJADQAJADAAAHIgCAGIgDADIgHAEQgGACAAADIADAOIAPAlIAOAjQAFAIADAAQABAAAFgIIALgdIAOgkQAEgNAAgFQABgFgKgHQgLgFAAgFQAAgGAJgDQAHgCAVgBQAXAAAHADQAIADAAAHQAAAIgLACIgHADQgKAFgMAgIgGANIgXA6QgeBNgTAWQgTAYgbAAQgNAAgJgIg");
	this.shape_24.setTransform(55.2,-32.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#006E46").s().p("AAgBWIgJgJIgIAEQgWAPgXAAQgaAAgRgQQgRgPAAgaQABgdAVgPQAVgRAmAAQAJAAAFADQAFADgBAHQAAAKgMAAQgSAAgLAIQgLAJAAAQQAAAOAKAJQAJAJAQAAQASAAAHgIQAHgIAAgTIAAhFQABgQgIgJQgGgJgNAAQgJAAgHAFQgIADgHAJIgEAEQgLAOgMAAQgIAAgEgEQgFgFABgIQgBgRAWgMQAVgMAhAAQAUAAAOAGQAPAFAJAKQAFAHACAMQACALABAaIAAA6QgBALACAFQACAFAEABIAFABQAMAEgBAGQAAAIgMAIQgMAHgQAAQgIAAgKgKg");
	this.shape_25.setTransform(36.4,-36.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#006E46").s().p("AhQBvQgVgZAAgnQAAgtAZgbQAZgcAmAAIANACQAGABADAEQADAEAAAEQAAAKgMAAIgFAAIgEgBQgVAAgMARQgMAQAAAdQAAAfANATQANAUAVgBQASAAALgKQALgLAAgVIAAgxIAAhUQAAgNgDgFQgDgFgGgCIgFgCQgMgDAAgHQAAgFAFgDQAFgDANgGIAVgFIARgCQAGAAADADQACAEAAAIIAAAJIgCBxIABBMQACARADADIAMAEQAKACAAAGQAAAJgbAJIgSAEIgNACQgFAAgDgDQgCgDAAgGIAAgJIAAgDIgBgBIgGADIgJAHQgLAIgJADQgLAFgLAAQgiAAgWgZg");
	this.shape_26.setTransform(16.2,-40.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#006E46").s().p("AgfCDQgJgDAAgJQAAgGAJgDIAEgCQAFgDACgGQABgGAAgOIAAgMIAAgPIAAgTQABgdgCgHQgCgJgDgCIgJgDQgLgEAAgGQAAgEAEgDQADgEAIgDIAcgJIASgDQAFAAACADQADAEgBAIIAAALIAAAJIgBAtIAAABIgBAtQAAASABAHQACAHAEACIAHADQAJAEAAAHQAAAHgJADQgIADgYAAQgcAAgIgDgAgVhcQgJgGABgKQAAgKAIgHQAJgIAMAAQALAAAIAHQAHAHAAAKQABAKgJAHQgIAHgMAAQgMAAgHgHg");
	this.shape_27.setTransform(-0.6,-40.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#006E46").s().p("AgeCDQgJgCAAgJQAAgFAIgEIAJgFQADgDABgLIACgkIAAgcIgBgiIAAgPQAAgtgBgOQgCgOgEgBIgLgFQgMgDAAgGQAAgFAEgDQAEgDANgEIAYgHIASgCQAGAAACADQACADAAAJIAAAOQgCBBAABBIABA/QABAOADADIAKAFQAJAEAAAGQAAAIgJACQgJADgYAAQgbAAgJgDg");
	this.shape_28.setTransform(-11.2,-40.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#006E46").s().p("AhCBFQgagbAAgpQAAgoAcgcQAbgbAoAAQAnAAAZAZQAaAaAAAoQAAApgbAdQgbAcgnABQgoAAgagbgAgig2QgLAPAAAYQAAAkAPAYQAPAZAWAAQARAAAMgPQALgPAAgZQAAgjgQgYQgQgZgUAAQgSAAgLAPg");
	this.shape_29.setTransform(-26.2,-36.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#006E46").s().p("AApCBQgKgDAAgIQAAgIALgEIAIgEQADgDACgLIABgrIgBgZIgBgIQgCgDgJgCQgJgBgiAAIgmABQgKABgEADIgCAFIAAAOIAAAPIABArQABALADADIAIAEQALAEAAAIQAAAIgKADQgKADgdAAQgcAAgLgDQgKgDAAgIQAAgIALgEIAJgEQADgDACgXQACgXAAg3IgChEQgBgbgDgEQgBgCgKgEQgKgEAAgIQAAgHAIgCQAIgDAhAAQAgAAAJADQAIACAAAHQAAAIgLAEIgIAEQgDADgCALIgBA2QAAAHAHADQAHADAaAAIAPAAIAngBQALgCADgCIACgEIABgHIAAgIIgBgtQgCgKgDgCIgIgEQgLgEAAgIQAAgHAIgCQAJgDAgAAQAhAAAIACQAIADAAAHQAAAIgLAEIgJAEQgDADgCAZQgCAYAAAxIACBHQABAbADAEQABADAKAEQAKADAAAIQAAAIgKADQgLADgcAAQgdAAgKgDg");
	this.shape_30.setTransform(-50.4,-40.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.smallbites, new cjs.Rectangle(-134.6,-64.2,269.2,126.5), null);


(lib.seventeenvideo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("AnwCvQhJAAgzg0Qg0gyAAhJQAAhHA0g0QAzgzBJAAIPhAAQBJAAAzAzQA0A0AABHQAABJg0AyQgzA0hJAAg");
	this.shape.setTransform(0,5,1.097,1.097);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenvideo, new cjs.Rectangle(-73.7,-14.2,147.5,38.4), null);


(lib.seventeenrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AnwCvQhJAAgzg0Qg0gyAAhJQAAhHA0g0QAzgzBJAAIPhAAQBJAAAzAzQA0A0AABHQAABJg0AyQgzA0hJAAg");
	this.shape.setTransform(0,5,1.097,1.097);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenrectangle, new cjs.Rectangle(-73.7,-14.2,147.5,38.4), null);


(lib.readytoserveshrimp = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AhbCAQgJgDAAgIQAAgGAIgDIAJgFQAEgEACgOQABgPAAgvIAAgeQAAgzgBgPQgCgPgFgCIgIgEQgMgDAAgGQAAgFAEgDQADgDAIgDIAagJQANgDAGAAQAGAAACADQACADAAAGIAAAJIABAEIAAABIAIgFIAHgFQAMgJAKgEQAKgEALAAQAjAAAXAZQAWAaAAApQAAAsgZAdQgZAdgnAAQgQAAgFgEQgHgFAAgIQAAgEADgDQADgDAGAAIAEABIAHABQAVAAAMgRQANgSAAgcQAAgggOgUQgOgUgVAAQgTAAgLALQgLALAAAcIAAB3IABATQABAIACACQACADAJACIAHADIAEADIACAGQAAAHgLADQgLACgbAAQgbAAgKgDg");
	this.shape.setTransform(51.3,30);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AiYBdQgJgDAAgIQAAgGAJgEIAFgCQAFgCACgHQACgGAAgPIAAgMIAAgQIAAgLQgBghgBgLQgCgKgEgCIgJgEQgLgDABgHQAAgEADgDIAMgGIAcgKIASgEQAFABADADQACADAAAHIAAAKIAAACIABABIAAABIACAAIAAgBIAFgDIACgCQAWgWAYAAQAIABAJACQAHADAIAFQAHAFAGAIQAIAJABAAQACgBAGgFIAIgJQAMgKAJgDQAKgFALAAQAVABARAIQAQAJAHAQQAIARAAA3IABASIgBAKIAAAJQAAALADAFQABAEAFADIAFACQAKAEAAAGQAAAIgJADQgJADgdAAQgcAAgIgDQgJgDAAgHQAAgHAKgEIAGgDQAEgCACgKQACgJAAgWQABg3gIgPQgHgPgUAAQgXAAgJATQgKATAAAtIAAAKQABAVABAGQADAHAEACIAGACQAIAEABAGQAAAIgJADQgJADgdAAQgZAAgJgDQgJgDAAgHQAAgHAKgDIAGgDQAFgDABgHQACgJAAgVQAAg7gIgPQgHgPgUAAQgLAAgIAGQgJAGgFAKQgEAJgCAPQgCAOAAAkQAAARACAHQACAGAEADIAGADQAKADAAAHQAAAHgJADQgKAEgYAAQgdAAgJgEg");
	this.shape_1.setTransform(23.3,26.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AggCGQgKgDAAgIQAAgGAKgEIAEgCQAFgCACgHQACgGAAgPIAAgMIgBgQIAAgTQABgegCgHQgBgKgEgBIgJgEQgMgDAAgHQAAgEAFgDQADgEAIgDIAcgJIATgEQAGABABADQADAEAAAIIAAALIgBAJIgBAvIAAACIgBAuQABASABAHQACAHAEADIAHADQAKADAAAHQAAAHgKADQgJAEgYAAQgdAAgIgEgAgWheQgJgGABgKQgBgMAKgHQAJgHAMgBQAMAAAIAIQAHAGAAALQAAAKgJAHQgIAIgNAAQgMAAgHgHg");
	this.shape_2.setTransform(0.8,22.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("Ag4BdQgJgDAAgIQAAgHAJgCIAFgDQAFgCACgHQACgGAAgPIgBgMIAAgQIAAgLQAAghgBgLQgCgKgEgCIgIgEQgMgDAAgHQAAgEAEgEQADgDAJgDIAZgIIARgEQAJAAADAaIAAAEIABABQAKgPAKgJQALgHAKgBQANABAIAHQAIAJAAAMQAAAOgGAHQgGAIgLAAIgJgCIgIgGIgEgHQgCgFgCAAQgNAAgFASQgFASAAA4QAAAQACAJQACAIAFADIAHACQAMAEAAAHQAAAHgLADQgKAEgZAAQgdAAgJgEg");
	this.shape_3.setTransform(-11.2,26.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AAaCHQgJgDAAgHQAAgIAKgDIAHgDQADgDACgIQACgIAAgTQAAg9gHgPQgIgPgUABQgJAAgJAFQgJAGgFAJQgEAJgCAOQgBAPgBAkQABAUABAFQABAGAFADIAHADQAJADAAAIQAAAHgJADQgKADgXAAQgeAAgJgDQgJgDAAgIQAAgHAJgDIAFgDQAFgDACgHQACgIAAgUIAAggIAAgcIgBhUQgCgWgCgDQgCgDgMgDQgLgDABgHQAAgEAEgFQAFgDARgGIATgFIARgCQAGAAADAEQACADAAAIIAAAIIgBBLIAAAJIAAAFIADABIAEgEIAGgHQAKgJALgGQAJgEAMAAQAgAAARAVQAPAVAAApIAAASIAAAiIAAAKQAAAKADAEQABAEAEACIAFACQAKAEAAAHQgBAIgIADQgJADgfAAQgXAAgKgDg");
	this.shape_4.setTransform(-30.3,22.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AguCIQgVgFgNgIQgIgEgFgQQgEgRAAgVQAAgIADgFQADgEAGAAQAJAAAJAQIAFAIQAMAVAOAKQAOAJATAAQAVAAAOgMQAOgMAAgSQAAgag3gZIgGgCQgugTgPgRQgPgRAAgaQAAgiAZgWQAZgVAoAAIAVABIAaAGIAIgFIAGgBQAFAAAEADQADADAEAHQAHALADAMQAEANAAAJQAAAGgDAEQgDADgFAAQgKAAgKgNIgCgEQgLgOgNgGQgMgHgQAAQgUAAgMAKQgMAKAAARQAAAPAKAKQAKAKAnASIAIADQAiAOAPANQAKAJAGANQAFANAAAPQAAAmgbAWQgbAVgvAAQgWAAgVgEg");
	this.shape_5.setTransform(-52.1,22.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("Ag8BHQgcgcAAgoQABgrAbgdQAcgcAqAAQAkAAAVAVQAWAUAAAkQAAALgEAEQgDAEgPAAIhHAAQgHAAgDgEQgDgCAAgGQAAgFADgCQADgDAHAAIAnAAIAJgCQACgBAAgEQABgSgNgNQgMgMgRAAQgWAAgLAUQgLAUAAAaQAAAeAPAVQAPAVAXAAQAOAAAKgDQAJgDAJgGIAHgGQAKgHAEgBQAFAAACAEQADACABAEQgBAFgEAGQgFAHgIAGQgRAOgPAFQgPAGgSAAQgnAAgagbg");
	this.shape_6.setTransform(121.8,-18);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AgTBPQgLgTgag9IgMgcQgNgkgIgEIgGgDQgLgEAAgHQAAgHAJgDQAKgDAfAAQAZAAAJADQAJADAAAHIgBAHIgEADIgGACQgHAEAAADIAEAQIAOAkIAPAkQAFAJACAAQADAAADgGIAJgQIAUgvQAHgSAAgHIgCgGIgEgFIgGgCQgIgDAAgGQAAgHAIgDQAJgDAXAAQAUAAAIADQAIADAAAHQAAAHgKADIgHADQgIAEgQAlIgFAMIgIARQgqBhgMAAQgIAAgKgSg");
	this.shape_7.setTransform(102.2,-17.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("Ag4BdQgJgDAAgIQAAgGAJgEIAFgCQAFgDACgGQACgGAAgOIgBgNIAAgPIAAgMQAAghgBgLQgCgKgEgDIgIgDQgMgDAAgGQAAgFAEgDQADgEAJgDIAZgIIARgDQAJAAADAZIAAAEIABAAQAKgOAKgJQALgHAKAAQANAAAIAHQAIAJAAANQAAANgGAHQgGAHgLABIgJgCIgIgGIgEgHQgCgFgCAAQgNAAgFASQgFASAAA4QAAARACAIQACAIAFACIAHADQAMADAAAIQAAAHgLADQgKADgZAAQgdAAgJgDg");
	this.shape_8.setTransform(85.6,-18.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E46").s().p("Ag9BHQgbgcAAgoQAAgrAcgdQAcgcApAAQAlAAAWAVQAUAUAAAkQAAALgDAEQgDAEgOAAIhIAAQgGAAgDgEQgEgCAAgGQAAgFAEgCQADgDAGAAIAmAAIAKgCQACgBAAgEQAAgSgMgNQgMgMgRAAQgWAAgLAUQgLAUAAAaQAAAeAPAVQAPAVAXAAQAOAAAJgDQAKgDAJgGIAHgGQAJgHAGgBQAEAAADAEQADACAAAEQAAAFgGAGQgEAHgIAGQgQAOgQAFQgPAGgRAAQgoAAgbgbg");
	this.shape_9.setTransform(68.1,-18);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E46").s().p("AguCIQgVgFgNgIQgIgEgFgQQgEgRAAgVQAAgIADgFQADgEAGAAQAJAAAJAQIAFAIQAMAVAOAKQAOAJATAAQAVAAAOgMQAOgMAAgSQAAgag3gZIgGgCQgugTgPgRQgPgRAAgaQAAgiAZgWQAZgVAoAAIAVABIAaAGIAIgFIAGgBQAFAAAEADQADADAEAHQAHALADAMQAEANAAAJQAAAGgDAEQgDADgFAAQgKAAgKgNIgCgEQgLgOgNgGQgMgHgQAAQgUAAgMAKQgMAKAAARQAAAPAKAKQAKAKAnASIAIADQAiAOAPANQAKAJAGANQAFANAAAPQAAAmgbAWQgbAVgvAAQgWAAgVgEg");
	this.shape_10.setTransform(47.2,-22.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E46").s().p("AgkAUQgHAAgBgCQgDgDAAgFIACgIIADgLIAGgHQACgBAJAAIAJAAIAQAAIAggBIAFAAQAGAAADACQACABAAAGQAAAJgFAKQgGAIgJABIgJgBIgKAAIgqACIgDAAg");
	this.shape_11.setTransform(30,-18.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E46").s().p("AhEBHQgbgcAAgqQAAgqAcgcQAdgcApAAQApAAAaAaQAaAbAAApQAAAqgdAeQgcAdgnAAQgpAAgbgbgAgjg3QgMAPAAAZQAAAkAQAaQAQAZAWAAQASAAALgQQAMgPAAgZQAAgkgQgZQgQgagWAAQgSAAgLAQg");
	this.shape_12.setTransform(13,-18);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E46").s().p("AgJBxQgKgDgGgGQgHgGgDgKQgCgLAAgcIAAhkIgSAAIgFgCIgCgFIAAgEQAAgGAUgRIAIgGIAHgHQATgRAIAAIAFABQAAABABAAQAAABAAAAQAAABABABQAAAAAAABIAAAkIAqAAQAEAAACABQACACAAAFIAAAEQAAAFgCADQgCACgEAAIgnAAIgDABIgBAFIAABcQAAAZAEAGQAEAGALAAQAGAAAJgDIANgDQAEAAADADQADABAAAFQAAAKgQAKQgQAJgUAAQgLAAgJgDg");
	this.shape_13.setTransform(-4.2,-19.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E46").s().p("AglAUQgFAAgDgCQgCgDAAgFIABgIIAFgLIAFgHQADgBAHAAIAJAAIARAAIAggBIAFAAQAGAAACACQADABAAAGQAAAJgGAKQgFAIgKABIgIgBIgLAAIgpACIgEAAg");
	this.shape_14.setTransform(-17.3,-18.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E46").s().p("AhWB8QgJgHAAgMQAAgKAHgHQAGgHAKAAIAIACIAFAEIAGAHQAEAIAEgBQAJAAALgNQAKgOgBgPQAAgQgNgdIgCgFIgehBIgRglQgEgGgLgGQgGgCgDgCQgCgEAAgEQAAgHAKgEQAKgDAbAAQAcAAAKADQAIADABAHIgCAGIgDAEIgHADQgHACAAAEIAEAOIAPAmIAOAjQAFAJADAAQACAAAFgIIALgfIAPglQAEgNAAgFQAAgGgLgFQgLgGABgFQgBgGAKgDQAIgDAVAAQAXAAAIADQAHADAAAHQABAHgLADIgIACQgKAGgMAhIgGAOIgYA8QgfBOgTAXQgUAYgbAAQgOAAgJgIg");
	this.shape_15.setTransform(-33,-14.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E46").s().p("AhSByQgWgZAAgpQAAguAagcQAZgdAoAAIANABQAGADADAEQADAEAAAFQAAAKgMgBIgFAAIgFAAQgVAAgMARQgNAQAAAdQAAAgAOAUQANAUAWAAQATAAAKgLQALgLAAgVIAAg0IAAhVQAAgOgCgEQgDgFgHgDIgFgBQgLgEAAgGQAAgGAEgDQAFgEAOgFIAVgGIASgCQAGAAADADQADAEAAAJIgBAJIgCBzIACBPQABASADADIANADQAKADAAAGQAAAKgbAIIgTAFIgOACQgGAAgCgEQgCgCAAgHIAAgJIgBgDIgBgBIgGADIgIAHQgLAIgKAEQgLAEgLAAQgkAAgWgZg");
	this.shape_16.setTransform(-53,-22.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E46").s().p("AAiBZIgKgKIgIAEQgYAPgWAAQgcAAgRgQQgRgQAAgZQAAgfAWgPQAWgRAnAAQAJAAAFACQAEADAAAHQABALgNAAQgTAAgLAJQgMAJAAAQQAAAPAKAJQAKAJARAAQARAAAIgIQAIgJAAgTIAAhHQAAgRgHgJQgHgJgMAAQgKAAgIAFQgIAEgIAIIgDAFQgMAOgNAAQgHAAgEgEQgEgFgBgIQABgSAVgMQAWgMAjAAQATAAAQAFQAPAGAHAKQAGAIACALQADAMAAAbIAAA7QAAALACAFQABAFAEABIAGACQAMADAAAHQAAAJgNAHQgNAHgQAAQgJAAgIgJg");
	this.shape_17.setTransform(-74.6,-18);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006E46").s().p("Ag8BHQgbgcAAgoQgBgrAcgdQAbgcArAAQAkAAAVAVQAWAUgBAkQAAALgDAEQgEAEgOAAIhHAAQgHAAgDgEQgDgCAAgGQAAgFADgCQADgDAHAAIAmAAIAKgCQACgBABgEQAAgSgNgNQgMgMgRAAQgWAAgLAUQgLAUAAAaQAAAeAPAVQAPAVAXAAQAOAAAKgDQAJgDAJgGIAHgGQAKgHAEgBQAFAAACAEQADACAAAEQAAAFgEAGQgFAHgIAGQgQAOgPAFQgQAGgSAAQgnAAgagbg");
	this.shape_18.setTransform(-94.8,-18);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006E46").s().p("AApBeQgSg8gOgMQgMgMgTAAQgPAAAAgMQAAgMAMAAQAfAAAPgMQAPgMAAgaQAAgYgPgNQgQgMgcAAQgPAAgFACQgGABgCAGIgCAQIgBAmIAABTIACA4QABANADADIAJAEQALAEAAAIQAAAIgKADQgKAEgeAAQgeAAgKgEQgLgDAAgIQAAgIAMgEIAIgFQAEgDACgWQACgWAAg7IgChHQgBgbgDgEQgCgCgKgEQgKgFAAgHQAAgGAGgEQAGgDAMAAIApAAIAmgBIAdgBQApAAAWASQAVARAAAiQAAAYgOATQgOASgaAHIAAACQAUAEAMAMQALANAJAeIAFATQAHAdALAAIAGAAIAHgBQADAAADADQADADAAAEQAAAJgLAFQgLAGgRAAQgmAAgMgsg");
	this.shape_19.setTransform(-117.8,-22.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.readytoserveshrimp, new cjs.Rectangle(-133.8,-46.7,267.6,93.4), null);


(lib.partystarted = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgvA4IgEgBQgBAAAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhmQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAABAAIApAAIALABIAMACQALAFAIAHQAJAIAEAKQADAFABAGQABAGAAAFQAAANgFALIgFAJIgIAIIgJAGIgKAGQgLADgMAAgAgegiQgBABAAAAQgBABAAAAQAAABAAABQAAAAAAABIAAA9QAAAAAAABQAAAAAAABQAAAAABABQAAAAABAAIAEACIAUAAQAIAAAHgCQAHgDAFgFQAGgFADgGQADgIAAgIQAAgIgDgGQgDgHgGgFQgFgEgHgDQgHgCgIgBIgUAAQAAAAgBABQgBAAAAAAQgBAAAAABQgBAAAAAAg");
	this.shape.setTransform(99.2,-0.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AgmA4IgDgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAAAIAAhpQAAAAAAAAQAAgBAAAAQAAAAABgBQAAAAABAAIADgBIBOAAIADABIABAEIAAAEIAAADIgBAFIgDACIg6AAIgDACIgBAEIAAAPQAAABAAAAQAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAQAAAAABABQAAAAABAAQAAAAABAAIAlAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAAAIACAEIAAAFIAAACQAAAFgEABIgkAAQgBAAgBABQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABAAAAQgBABAAABQAAAAAAABQAAAAAAABIAAARQAAAAAAABQAAAAAAABQAAAAAAABQABAAAAAAQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIA5AAQAEACAAAFIAAADIgBAFIgBADQAAAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_1.setTransform(87.3,-0.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AgBA5IgGgBQgCgBAAgDIAAhTQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQgBgBgEAAIgJAAIgJAAIgEAAQgDAAgCgCIgBgGIAAgDIABgEIABgDIAEgBIBNAAQAEAAABACIABAGIAAACIgBAFIgCADQAAAAAAABQgBAAAAAAQAAAAgBAAQAAAAgBAAIgWAAIgFABQAAABgBAAQAAABAAAAQgBABAAABQAAAAAAABIAABSIgBAEIgDABIgEABg");
	this.shape_2.setTransform(76.6,-0.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("AAcA6IgCgCIgCgBIgCgBIgUgdIgCgFIgFgBIgOAAQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABgBAAQAAAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAcQAAABAAAAQAAAAAAABQgBAAAAAAQAAABAAAAIgFABIgEABIgEAAQgDAAgCgCQgCgBAAgEIABhnQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAIADgBIAwAAQAIgBAHADQAIADAGAFQAFAFADAHQADAHAAAJQAAAJgDAHQgFAEgDAEIgJAGQgDACAAADIAAACIAEAHIAHAJIAGAJIADAGQAAAAgBAAQAAABAAAAQAAABAAAAQgBABAAAAIgEACIgDACIgFABgAgXgkQAAABgBAAQAAABAAAAQgBABAAAAQAAABAAABIAAAZQAAABAAABQAAABABAAQAAABAAAAQABABAAAAQADABADAAIAWAAIAIgBQAEgBADgCQADgCACgEQACgDAAgFQgBgKgGgEQgDgCgEgCQgDgBgFAAIgWAAQgDAAgDABg");
	this.shape_3.setTransform(66.6,-0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AAsA5IgCAAIgHAAQgDgBgBgDIgHgPIgBgDIgDgBIgmAAIgCABIgBABIgCABIgBABIgGAPIgCACIgDABIgEABIgCAAIgEAAIgDAAIgDgCQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAvhqQAAAAABgBQAAAAAAAAQABgBAAAAQAAAAABAAIADgBIAFAAQAAAAABABQABAAAAAAQABABAAAAQAAABAAAAIAtBqIAAABQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgDABgAgBgRIgBACIgBADIgCAFIgDAHIgDAFIgBAFIgBACIABADIACABIAWAAIACgBIABgCIgCgFIgEgJIgEgJIgCgGIgDgBg");
	this.shape_4.setTransform(54.8,-0.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AgBA5IgGgBQgCgBAAgDIAAhTQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQgBgBgEAAIgJAAIgJAAIgEAAQgDAAgCgCIgBgGIAAgDIABgEIABgDIAEgBIBNAAQAEAAABACIABAGIAAACIgBAFIgCADQAAAAAAABQgBAAAAAAQAAAAgBAAQAAAAgBAAIgWAAIgFABQAAABgBAAQAAABAAAAQgBABAAABQAAAAAAABIAABSIgBAEIgDABIgEABg");
	this.shape_5.setTransform(44.6,-0.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AgZA2QgLgEgKgJIgBgCIAAgCIABgEIADgEIAFgDIADgBQADAAADACIAHAFIAKAFQAFACAHAAIAIgBQAFAAAEgCQAEgCADgDQADgEgBgFQAAgEgCgDQgEgDgFgBIgLgDIgNgBIgNgDIgMgEQgFgEgDgGQgDgFAAgJQAAgJAEgGQAFgHAHgEQAGgEAJgCQAIgCAGAAIAMABIALACIAKAFQAGADAEADIAAACIABACIgBAEIgEAEIgFACIgDABIgEAAQgGgFgGgDQgIgDgHAAIgHAAIgIADIgGAFQgCADAAAEQgBAGAGADQAFADAJABIAQACQAKACAIADQAIADAFAFQAGAGAAAMQAAAKgFAHQgFAHgHAFQgHAEgJADQgJACgHAAQgNAAgMgFg");
	this.shape_6.setTransform(34.5,-0.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AgDA7IgEgBIgCgBIgBgCIAAgoIAAgHIgDgGIghgxIAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAAAgBIAEgDIAEgCIAEAAIAEAAIACADIAXAkIACACIACABIACgBIADgCIAWgkIAEgDIADgBIAEABIAEABIADADIACADIAAACIgBABIggAyIgDAGIgBADIAAACIAAAoQgCAEgDABIgGAAg");
	this.shape_7.setTransform(19.1,-0.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("AgBA5IgGgBQgCgBAAgDIAAhTQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQgBgBgEAAIgJAAIgJAAIgEAAQgDAAgCgCIgBgGIAAgDIABgEIABgDIAEgBIBNAAQAEAAABACIABAGIAAACIgBAFIgCADQAAAAAAABQgBAAAAAAQAAAAgBAAQAAAAgBAAIgWAAIgFABQAAABgBAAQAAABAAAAQAAABgBABQAAAAAAABIAABSIgBAEIgDABIgEABg");
	this.shape_8.setTransform(9.2,-0.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E46").s().p("AAdA6IgDgCIgDgBIgBgBIgTgdIgDgFIgFgBIgOAAQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAcQAAABAAAAQAAAAAAABQgBAAAAAAQAAABAAAAIgFABIgEABIgEAAQgDAAgCgCQgCgBAAgEIAAhnQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAAAIADgBIAvAAQAKgBAGADQAIADAGAFQAFAFADAHQADAHAAAJQAAAJgEAHQgEAEgDAEIgIAGQgEACAAADIAAACIAFAHIAGAJIAGAJIACAGQAAAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgDACIgFACIgDABgAgXgkQgBABAAAAQAAABgBAAQAAABAAAAQAAABAAABIAAAZQAAABAAABQAAABAAAAQABABAAAAQAAABABAAQADABADAAIAWAAIAIgBQAEgBADgCQADgCABgEQACgDABgFQAAgKgHgEQgDgCgEgCQgEgBgEAAIgWAAQgDAAgDABg");
	this.shape_9.setTransform(-0.8,-0.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E46").s().p("AAsA5IgCAAIgHAAQgCgBgCgDIgGgPIgCgDIgEgBIglAAIgBABIgCABIgCABIgBABIgGAPIgCACIgDABIgDABIgEAAIgDAAIgDAAIgDgCQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIAvhqQAAAAABgBQAAAAAAAAQABgBAAAAQAAAAABAAIADgBIAFAAQAAAAABABQABAAAAAAQABABAAAAQAAABAAAAIAtBqIAAABQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgEABgAAAgRIgBACIgCADIgCAFIgDAHIgCAFIgCAFIgCACIACADIACABIAVAAIADgBIABgCIgCgFIgEgJIgDgJIgDgGIgDgBg");
	this.shape_10.setTransform(-12.5,-0.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E46").s().p("AgnA6QgFAAgCgFIAAhrQAAAAAAAAQAAgBAAAAQABAAAAAAQAAgBABAAIADAAIAwAAQAIAAAHABQAHADAGAFQAGAEADAHQADAGAAAJIgBAFIgBAGQgEAKgIAFQgHAEgJACQgJACgKAAIgTAAIgCAAIgBACIgBADIAAAjIgDADIgDABIgFABgAgYgjQAAABAAAAQgBABAAAAQAAABAAAAQAAABAAABIAAATQAAAAAAAAQAAABAAAAQAAABABAAQAAABAAAAQABAAAAABQAAAAABAAQAAAAABAAQAAAAABAAIAbAAIAHgBIAGgCQADgCABgEQACgDAAgDQAAgDgCgDIgEgFIgFgDIgGgBIgdAAQAAAAgBAAQAAAAgBAAQAAABgBAAQAAABgBAAg");
	this.shape_11.setTransform(-23,-0.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E46").s().p("AgmA4IgDgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAAAIAAhpQAAAAAAAAQAAgBAAAAQAAAAABgBQAAAAABAAIADgBIBOAAIADABIABAEIABAEIAAADIgCAFIgDACIg6AAIgDACIgCAEIAAAPQABABAAAAQAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAQAAAAABABQAAAAABAAQAAAAABAAIAlAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAAAIACAEIAAAFIAAACQAAAFgEABIgkAAQgBAAAAABQgBAAAAAAQgBAAgBABQAAAAgBAAQAAABAAAAQgBABAAABQAAAAAAABQgBAAAAABIAAARQABAAAAABQAAAAAAABQAAAAAAABQABAAAAAAQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIA5AAQAEACAAAFIAAADIgBAFIgBADQAAAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_12.setTransform(-39,-0.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E46").s().p("AAeA5IgEgCIAAgoQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQAAAAgBgBQAAAAgBAAQAAgBgBAAQgBAAAAAAIgmAAQgCAAgDADQAAAAgBABQAAAAAAABQgBAAAAABQAAABAAAAIAAAnQAAABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAIgDABIgFAAIgEAAIgEgBIgDgDIAAhrIADgDIAEgBIAEAAIAEAAQAEAAACAEIAAAkQAAABAAAAQAAABABABQAAAAAAABQAAAAABABQAAAAABAAQAAABAAAAQABAAABAAQAAAAABAAIAmAAQABAAAAAAQABAAABAAQAAAAABgBQAAAAABAAQAAgBABAAQAAgBAAAAQABgBAAgBQAAAAAAgBIAAgkQACgDADgBIAHAAIAFABIAEADIgBBrQgBAEgDAAIgHAAg");
	this.shape_13.setTransform(-51.1,-0.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E46").s().p("AgBA5IgGgBQgCgBAAgDIAAhTQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQgBgBgEAAIgJAAIgJAAIgEAAQgDAAgCgCIgBgGIAAgDIABgEIABgDIAEgBIBNAAQAEAAABACIABAGIAAACIgBAFIgCADQAAAAAAABQgBAAAAAAQAAAAgBAAQAAAAgBAAIgWAAIgFABQAAABgBAAQAAABAAAAQAAABgBABQAAAAAAABIAABSIgBAEIgDABIgEABg");
	this.shape_14.setTransform(-62.1,-0.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E46").s().p("AgBA5IgGgBQgCgBAAgDIAAhTQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQgBgBgEAAIgJAAIgJAAIgEAAQgDAAgCgCIgBgGIAAgDIABgEIABgDIAEgBIBNAAQAEAAABACIABAGIAAACIgBAFIgCADQAAAAAAABQgBAAAAAAQAAAAgBAAQAAAAgBAAIgWAAIgFABQAAABgBAAQAAABAAAAQgBABAAABQAAAAAAABIAABSIgBAEIgDABIgEABg");
	this.shape_15.setTransform(-76.2,-0.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E46").s().p("AglA4IgEgBQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAAAIAAhpQAAAAABAAQAAgBAAAAQAAAAABgBQAAAAAAAAIAEgBIBPAAIACABIABAEIAAAEIAAADIgBAFIgCACIg7AAIgDACIgBAEIAAAPQAAABAAAAQAAABAAAAQAAABAAAAQABAAAAABQAAAAABAAQAAAAABABQAAAAABAAQAAAAABAAIAlAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAABAAIABAEIAAAFIAAACQAAAFgEABIglAAQAAAAgBABQAAAAgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQgBABAAABQAAAAAAABQAAAAAAABIAAARQAAAAAAABQAAAAAAABQAAAAAAABQABAAAAAAQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAIA6AAQADACAAAFIAAADIgBAFIAAADQgBAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_16.setTransform(-85.8,-0.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E46").s().p("AgIA6QgGgBgGgDQgFgCgFgDIgJgHIgIgIIgFgKQgFgMAAgMQAAgFABgGQABgGADgGQAFgKAIgIIAJgHIAKgGIAMgDIALgBIANACQAGABAGACQAMAGAJAKIAAACIgBADIgEAFIgEADIgEABQgCAAgDgCIgGgFIgJgGQgFgCgIAAQgHAAgHADQgHADgGAFQgFAGgDAHQgDAHAAAHQAAAIADAHQADAHAFAFQAGAGAHADQAHADAHAAIAIgBIAIgBIAGgEQAEgCACgEIAAgCQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAAAAAgBIgEgBIgUAAQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAgBAAAAIgCgDIAAgFIAAgDIABgFIADgCIAwAAIABABIACABQACAFAAAGIAAAEIgBAFQgDAJgGAGQgGAHgGAFQgIAEgIACQgIADgJAAIgLgBg");
	this.shape_17.setTransform(-98.7,-0.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.partystarted, new cjs.Rectangle(-107.2,-10.2,214.5,20.6), null);


(lib.partyperfect = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgNBiIgUgEIgGAEIgGABIgEgBIgEgCQgGgGgFgPQgGgPAAgOQAAgGAEgEQADgEAFAAQAIAAAJAPIAHAMQAGAHAKAEQAJAFALAAQAMAAAHgHQAIgGAAgKQAAgQgfgPIgLgGQgdgOgLgMQgKgMAAgSQAAgYARgQQARgPAbAAIANABIANACIAJgEIAGgBQAJAAAJAPQAJAPAAAQQAAAHgDAEQgDADgGAAQgEAAgEgDQgEgEgGgJQgHgLgIgFQgHgFgLAAQgKAAgGAGQgHAHAAAKQAAAIAHAHQAHAGAWAMIACABQA1AZAAAfQAAAagUARQgVASgeAAg");
	this.shape.setTransform(113.6,26.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AgfCHQgJgDAAgIQAAgGAIgEIAJgFQADgDACgLIABgmIAAgdIAAgjIAAgOQAAgvgCgOQgCgOgEgCIgLgEQgMgDAAgHQAAgFAEgDQADgDAOgFIAZgHIATgCQAFAAADADQACAEAAAJIgBAOQgCBDAABDIACBAQABAOADAEIAKAFQAJAEAAAHQAAAHgJADQgKADgYAAQgcAAgJgDg");
	this.shape_1.setTransform(100,22.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AALAUIgWg6QgLgbgJgEIgFgCQgLgFAAgGQAAgIAJgDQAKgDAdAAQAaAAAJADQAJADAAAIIgBAFIgEAEIgGACQgIADAAAFIAEAMIAPAnIAQAkQAFAJACAAQADgBADgFIAIgQIAVgvQAHgSAAgHIgCgGIgEgEIgGgCQgIgEAAgGQAAgHAIgDQAJgDAXAAQAUAAAIADQAIADAAAHQAAAIgKADIgGACQgJAEgRAoIgEAJIgIARQgrBhgMAAQgNAAghhNgAhuAKIgFgLIgNggQgMgggIgEIgGgCQgLgFAAgGQAAgIAKgDQAJgDAfAAQAZAAAJADQAJADAAAIIgBAFIgDAEIgGACQgIADAAAFIAEAQIAOAjIAQAjQAFAKACAAQAGAAAFgMIAHgNIAEgGQACgCAEAAQAFAAADACQACADAAAFQAAAFgFALQgUArgIAOQgJAOgHAAQgNAAglhXg");
	this.shape_2.setTransform(79.9,27);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("AhEBGQgbgbAAgqQAAgqAdgcQAcgcApAAQApAAAaAbQAaAaAAApQAAArgcAdQgdAdgnAAQgpAAgbgcgAgjg3QgMAPAAAZQAAAkAQAaQAQAZAWAAQASAAALgPQAMgQAAgaQAAgjgQgaQgQgYgWAAQgSAAgLAPg");
	this.shape_3.setTransform(53.6,26.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AgNCIIglgCIgSABIgVAAQgOAAgGgDQgHgEAAgHQAAgHAKgEQAKgEACgCQADgEABgcIAChJIgChHQgBgbgDgEQgCgCgKgEQgKgFAAgHQAAgHAGgDQAFgDAMAAIAUAAIAWAAIAlgBIAegBQAoAAAWARQAWARAAAgQAAAZgQAQQgPAQgeAFQAmAEAUARQAUASAAAgQAAAjgZATQgZAUgtAAgAgchsQgGABgCADQgDAFgBASIgBA2IAABOIABAlQABAKADAFQACAEAKACQAJACAPAAQAeAAARgMQAQgNAAgZQAAgbgSgMQgTgNghAAQgQAAgBgLQABgNAQAAQAYAAAQgLQAPgLAAgZQABgYgQgMQgOgMgeAAg");
	this.shape_4.setTransform(29.9,22.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("Ag8BxQgbgcAAgoQgBgsAcgcQAbgcArAAQAkAAAVAVQAWAUgBAiQAAAMgDAEQgEADgOAAIhHAAQgHAAgDgDQgDgDAAgFQAAgFADgCQADgDAHAAIAmAAIAKgCQACgBABgEQAAgRgNgNQgMgMgRAAQgWAAgLAUQgLASAAAbQAAAeAPAWQAPAVAXAAQAOAAAKgDQAJgDAJgHIAHgFQAKgIAEAAQAFAAADADQACADAAAEQAAAEgEAHQgFAGgIAHQgQANgPAGQgQAGgSAAQgnAAgagbgAgPhKQgDAAgEgGQgEgGAAgEIABgDIAEgDIA/gnIAGgDIAEgBQAGAAAFAIQAGAHgBAHQABAGgLAFIgBAAIhDAfIgDABIgCAAg");
	this.shape_5.setTransform(-3,22.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AgJBxQgKgDgGgGQgHgGgDgLQgCgKAAgcIAAhkIgSAAIgFgBIgCgGIAAgEQAAgGAUgRIAIgHIAHgGQATgRAIAAIAFACQAAAAABAAQAAABAAAAQABABAAABQAAAAAAABIAAAjIAqAAQAEAAACACQACACAAAFIAAAFQAAAEgCADQgCACgEAAIgnAAIgDABIgBAFIAABdQAAAXAEAHQAEAGALAAQAGAAAJgDIANgDQAEAAADADQADACAAADQAAALgQAJQgQAKgUAAQgLAAgJgDg");
	this.shape_6.setTransform(-19.6,24.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AghCGQgJgDAAgIQAAgGAJgEIAFgCQAFgCACgHQACgGAAgPIAAgMIgBgQIAAgTQAAgegBgHQgBgKgEgBIgJgEQgMgDAAgHQABgEAEgDQADgEAIgDIAcgJIAUgEQAEABACADQADAEAAAIIAAALIAAAJIgCAvIAAACIgBAuQAAASACAHQABAHAFADIAHADQAJADAAAHQAAAHgJADQgJAEgZAAQgbAAgKgEgAgXheQgHgGgBgKQABgMAIgHQAKgHAMgBQALAAAJAIQAHAGABALQgBAKgIAHQgJAIgNAAQgMAAgIgHg");
	this.shape_7.setTransform(-31.7,22.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("AhSByQgWgaAAgpQAAgtAagcQAZgdAoAAIANACQAGABADAFQADADAAAGQAAAJgMABIgFgBIgFAAQgVAAgMARQgNAQAAAeQAAAfAOAUQANAUAWAAQATAAAKgLQALgLAAgVIAAg0IAAhVQAAgNgCgGQgDgFgHgCIgFgCQgLgDAAgHQAAgEAEgFQAFgDAOgFIAVgGIASgCQAGAAADAEQADADAAAIIgBAKIgCBzIACBPQABASADACIANAFQAKACAAAHQAAAIgbAJIgTAFIgOABQgGAAgCgDQgCgCAAgHIAAgIIgBgEIgBgCIgGAFIgIAGQgLAIgKAEQgLAEgLAAQgkAAgWgZg");
	this.shape_8.setTransform(-47.5,22.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E46").s().p("AAoBfQgCgCAAgHIAAgNIAAgBIgBAAQgCAAgEAFIgDACQgJAKgMAEQgJAFgOAAQgPAAgMgGQgNgFgIgKQgJgKgDgQQgEgPAAgnIAAgNIAAgOIAAgEQAAgPgCgEQgCgFgHgCIgIgDQgKgCAAgHQAAgFAEgDQAEgDANgFIAZgHIAUgCQAFAAACAEQADADAAAJIAAAHIgDBGQABAmAHAOQAJAPASAAQAVAAAKgTQAJgTAAgtIAAgOQAAgPgCgEQgCgFgGgCIgIgDQgLgCAAgHQAAgFAEgDQADgDAOgFIAZgHIAUgCQAFAAADADQACAEAAAJIgBAKIgBBNIAAAgIABAMQABAIAKAEIAEABQAKADAAAHQAAAEgDADQgDADgJADIgbAJQgNADgGAAQgGAAgDgDg");
	this.shape_9.setTransform(-70.6,26.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E46").s().p("Ag4BdQgJgDAAgIQAAgHAJgCIAFgDQAFgCACgHQACgGAAgPIgBgMIAAgQIAAgLQAAghgBgLQgCgKgEgCIgIgEQgMgDAAgHQAAgEAEgEQADgDAJgDIAZgIIARgEQAJAAADAaIAAAEIABABQAKgPAKgJQALgHAKgBQANABAIAHQAIAJAAAMQAAAOgGAHQgGAIgLAAIgJgCIgIgGIgEgHQgCgFgCAAQgNAAgFASQgFASAAA4QAAAQACAJQACAIAFADIAHACQAMAEAAAHQAAAHgLADQgKAEgZAAQgdAAgJgEg");
	this.shape_10.setTransform(-88.4,26.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E46").s().p("AgcCDQgagJgTgRQgWgUgLgcQgMgcAAggQABgaAHgXQAIgXAPgSQASgWAbgMQAagMAfAAIAWABIAlAIIAEgBIAOgDIAHACIAFAFQAGAKAEAPQAEAOgBALQAAAIgCAEQgDAEgGAAQgJAAgOgRIgMgNQgKgLgPgFQgPgGgRAAQglAAgVAZQgVAZAAAsQAAA3AbAkQAbAkAoAAQARAAAPgGQAOgFAKgJIAJgLQAIgLAFAAQAFAAAEAFQACAFAAAJQABARgFALQgFAKgJAAIgCAAIgCgBQgRAJgSAFQgSAEgTAAQgbAAgZgJg");
	this.shape_11.setTransform(-108.7,22.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E46").s().p("AgJBxQgKgDgGgGQgHgGgDgKQgCgLAAgcIAAhkIgSAAIgFgCIgCgFIAAgEQAAgGAUgRIAIgGIAHgHQATgRAIAAIAFABQAAABABAAQAAABAAAAQAAABABABQAAAAAAABIAAAkIAqAAQAEAAACABQACACAAAFIAAAEQAAAFgCADQgCACgEAAIgnAAIgDABIgBAFIAABcQAAAZAEAGQAEAGALAAQAGAAAJgDIANgDQAEAAADADQADABAAAFQAAAKgQAKQgQAJgUAAQgLAAgJgDg");
	this.shape_12.setTransform(104.4,-19.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E46").s().p("Ag7BHQgbgcAAgoQAAgqAdgdQAcgdApAAQAfAAAWARQAWAPAAAWQAAAIgGAHQgHAEgJAAQgKABgFgFQgGgEgHgPQgGgOgHgGQgHgFgMAAQgUAAgNARQgMAQAAAdQAAAgASAWQARAUAaAAQAJABAJgDQAIgDAHgFIAIgFQAKgIAFAAQAEAAADADQACABAAAEQAAAGgEAGQgEAHgGAFQgPANgQAGQgQAGgTAAQgmAAgbgbg");
	this.shape_13.setTransform(88.1,-18);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E46").s().p("Ag8BHQgbgcAAgoQAAgrAbgdQAbgcArAAQAkAAAWAVQAVAUgBAkQABALgEAEQgEAEgNAAIhIAAQgGAAgDgEQgEgCAAgGQAAgFAEgCQADgDAGAAIAmAAIAKgCQADgBAAgEQAAgSgNgNQgMgMgRAAQgWAAgLAUQgLAUAAAaQAAAeAPAVQAPAVAXAAQAOAAAKgDQAJgDAJgGIAHgGQAKgHAEgBQAFAAADAEQACACAAAEQAAAFgEAGQgFAHgIAGQgQAOgPAFQgQAGgSAAQgnAAgagbg");
	this.shape_14.setTransform(68.4,-18);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E46").s().p("Ag0CHQgJgDAAgIQgBgGAKgDIAEgCQAFgDABgGQACgGAAgQIAAgSIAAhaIgVAAQgEAAgCgCQgCgCAAgFIAAgFQAAgEACgCQACgCAEAAIAUAAIgCgPIAAgOQAAgcASgQQAQgQAeAAQAWAAANAKQAOAJAAAPQAAAJgFAFQgFAEgJAAQgGAAgFgCQgFgDgDgFIgEgHQgHgNgLAAQgHAAgDAEQgEAFAAAHIAEAVQAEARAAANIAbAAQAFAAACABQABACAAAFIAAAFQAAAFgBACQgDACgEAAIgbAAIAABgQAAAYABAIQACAHAEACIAIADQALADgBAIQAAAHgJADQgJADgbAAQgbAAgJgDg");
	this.shape_15.setTransform(54.8,-22.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E46").s().p("Ag4BdQgJgDAAgIQAAgGAJgEIAFgCQAFgDACgGQACgGAAgOIgBgNIAAgPIAAgMQAAghgBgLQgCgKgEgDIgIgDQgMgDAAgGQAAgFAEgDQADgEAJgDIAZgIIARgDQAJAAADAZIAAAEIABAAQAKgOAKgJQALgHAKAAQANAAAIAHQAIAJAAANQAAANgGAHQgGAHgLABIgJgCIgIgGIgEgHQgCgFgCAAQgNAAgFASQgFASAAA4QAAARACAIQACAIAFACIAHADQAMADAAAIQAAAHgLADQgKADgZAAQgdAAgJgDg");
	this.shape_16.setTransform(41.1,-18.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E46").s().p("Ag9BHQgbgcAAgoQAAgrAcgdQAcgcApAAQAlAAAWAVQAUAUAAAkQAAALgDAEQgDAEgOAAIhIAAQgGAAgDgEQgEgCAAgGQAAgFAEgCQADgDAGAAIAnAAIAJgCQACgBAAgEQAAgSgMgNQgMgMgRAAQgWAAgLAUQgLAUAAAaQAAAeAPAVQAPAVAXAAQAOAAAJgDQAKgDAJgGIAHgGQAJgHAGgBQAEAAADAEQADACAAAEQAAAFgGAGQgEAHgIAGQgQAOgQAFQgPAGgRAAQgoAAgbgbg");
	this.shape_17.setTransform(23.6,-18);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006E46").s().p("AhhCFQgLgDABgIQAAgIAMgEIAIgFQADgDACgWQACgWAAg7IgChHQgBgbgDgEQgCgCgJgEQgKgFAAgHQAAgGAFgEQAGgDAMAAIATAAIAWAAIAmgBIAdgBQAqAAAWASQAUASABAkQAAAngaAVQgaAUgyAAQgTAAAAgNQABgMAPAAQAYAAAOgNQAPgMAAgcQAAgagPgMQgOgMgfAAQgOAAgFACQgGACgCAFIgCARIAAAnIAABTIABA1QABAOAEADIAIAEQAMAEAAAIQgBAIgJADQgLAEgeAAQgeAAgKgEg");
	this.shape_18.setTransform(2.8,-22.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006E46").s().p("AgkAUQgHAAgBgCQgDgDAAgFIACgIIADgLIAGgHQADgBAHAAIAJAAIARAAIAggBIAFAAQAGAAACACQADABAAAGQAAAJgFAKQgHAIgJABIgIgBIgKAAIgqACIgDAAg");
	this.shape_19.setTransform(-15.3,-18.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#006E46").s().p("AhWB8QgJgHAAgMQAAgKAHgHQAGgHAJAAIAIACIAHAEIAEAHQAGAIADgBQAKAAAKgNQAJgOABgPQAAgQgOgdIgCgFIgehBIgRglQgDgGgMgGQgGgCgDgCQgBgEAAgEQAAgHAJgEQAKgDAbAAQAcAAAJADQAKADgBAHIgBAGIgDAEIgHADQgHACAAAEIAEAOIAPAmIAOAjQAFAJADAAQACAAAFgIIAMgfIANglQAFgNAAgFQAAgGgKgFQgLgGAAgFQAAgGAJgDQAIgDAVAAQAXAAAHADQAJADgBAHQAAAHgKADIgIACQgLAGgLAhIgGAOIgYA8QgfBOgTAXQgUAYgcAAQgNAAgJgIg");
	this.shape_20.setTransform(-31,-14.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#006E46").s().p("AgJBxQgKgDgGgGQgHgGgDgKQgCgLAAgcIAAhkIgSAAIgFgCIgCgFIAAgEQAAgGAUgRIAIgGIAHgHQATgRAIAAIAFABQAAABABAAQAAABAAAAQAAABABABQAAAAAAABIAAAkIAqAAQAEAAACABQACACAAAFIAAAEQAAAFgCADQgCACgEAAIgnAAIgDABIgBAFIAABcQAAAZAEAGQAEAGALAAQAGAAAJgDIANgDQAEAAADADQADABAAAFQAAAKgQAKQgQAJgUAAQgLAAgJgDg");
	this.shape_21.setTransform(-47.2,-19.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#006E46").s().p("Ag4BdQgJgDAAgIQAAgGAJgEIAFgCQAFgDACgGQACgGAAgOIgBgNIAAgPIAAgMQAAghgBgLQgCgKgEgDIgIgDQgMgDAAgGQAAgFAEgDQADgEAJgDIAZgIIARgDQAJAAADAZIAAAEIABAAQAKgOAKgJQALgHAKAAQANAAAIAHQAIAJAAANQAAANgGAHQgGAHgLABIgJgCIgIgGIgEgHQgCgFgCAAQgNAAgFASQgFASAAA4QAAARACAIQACAIAFACIAHADQAMADAAAIQAAAHgLADQgKADgZAAQgdAAgJgDg");
	this.shape_22.setTransform(-60.7,-18.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#006E46").s().p("AAhBZIgKgKIgIAEQgWAPgYAAQgbAAgRgQQgRgQAAgZQAAgfAWgPQAWgRAnAAQAJAAAEACQAGADAAAHQgBALgNAAQgRAAgMAJQgLAJAAAQQAAAPAKAJQAKAJAQAAQASAAAIgIQAHgJAAgTIAAhHQAAgRgHgJQgHgJgNAAQgJAAgIAFQgIAEgHAIIgEAFQgLAOgNAAQgIAAgEgEQgEgFAAgIQgBgSAWgMQAWgMAjAAQATAAAQAFQAPAGAHAKQAGAIACALQADAMAAAbIAAA7QAAALABAFQADAFADABIAGACQAMADAAAHQAAAJgMAHQgNAHgRAAQgJAAgJgJg");
	this.shape_23.setTransform(-78.1,-18);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#006E46").s().p("AhhCFQgLgDAAgIQABgIAMgEIAHgFQAFgDABgWQACgWAAg7IgChHQgBgbgCgEQgCgCgLgEQgJgFgBgHQAAgGAHgEQAFgDAMAAIATAAIAWAAIAmgBIAdgBQAqAAAWASQAUASAAAkQAAAngaAVQgZAUgyAAQgTAAABgNQAAgMAQAAQAXAAAOgNQAPgMAAgcQAAgagPgMQgPgMgdAAQgOAAgGACQgFACgCAFIgCARIgBAnIAABTIABA1QABAOADADIAJAEQAMAEgBAIQAAAIgKADQgKAEgeAAQgdAAgLgEg");
	this.shape_24.setTransform(-99.2,-22.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.partyperfect, new cjs.Rectangle(-123.9,-46.7,247.9,93.4), null);


(lib.ordernow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AATAmIgTg4IgSA4IgQAAIgYhLIAPAAIARA5IABAAIASg5IAPAAIASA5IASg5IAQAAIgaBLg");
	this.shape.setTransform(32.7,8.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgPAlQgIgDgGgFQgFgGgDgHQgDgHAAgJQAAgIADgHQADgIAFgEQAGgGAIgDQAHgDAIAAQAJAAAHADQAHADAGAGQAFAEAEAIQADAHAAAIQAAAJgDAHQgEAHgFAGQgGAFgHADQgHADgJAAQgIAAgHgDgAgKgYQgFACgDAEQgDAEgCAFQgBAEAAAFQAAAGABAEQACAFADAEQADAEAFACQAFACAFABQAGgBAFgCQAEgCAEgEQADgEABgFQACgEAAgGQAAgFgCgEQgBgFgDgEQgEgEgEgCQgFgDgGABQgFgBgFADg");
	this.shape_1.setTransform(21.6,8.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AATAnIAAgpIgBgJIgCgHQgCgEgDgCQgEgBgFAAQgIgBgGAIQgGAGAAAMIAAAnIgOAAIAAg6IAAgIIgBgJIAOAAIAAAGIAAAGIABAAIAEgFIAGgEIAHgEIAHgBQAHAAAFADQAGACADAEQAEAFACAFQABAGAAAGIAAAug");
	this.shape_2.setTransform(12.1,8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgnA6IAAhxIAOAAIAAAMIABAAQAEgGAHgEQAHgEAIAAQAJAAAHADQAHADAFAFQAFAGACAHQADAHAAAJQAAAIgDAHQgCAHgFAFQgFAGgHADQgHADgJAAQgHAAgHgEQgIgDgEgHIAAAAIAAAygAgKgqQgFACgDAEQgEADgBAFQgCAFAAAGQAAAFACAFQABAFAEADQADAEAFACQAFACAFAAQAGAAAEgCQAFgCADgEIAFgIIACgKQAAgGgCgFQgCgFgDgDQgDgEgFgCQgEgDgGAAQgFAAgFADg");
	this.shape_3.setTransform(-1.4,9.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgQAlQgHgDgFgFQgGgGgDgHQgDgHAAgJQAAgIADgHQADgIAGgEQAFgGAHgDQAIgDAIAAQAIAAAIADQAHADAGAGQAFAEADAIQAEAHAAAIQAAAJgEAHQgDAHgFAGQgGAFgHADQgIADgIAAQgIAAgIgDgAgKgYQgEACgEAEQgDAEgCAFQgCAEAAAFQAAAGACAEQACAFADAEQAEAEAEACQAFACAFABQAGgBAEgCQAGgCACgEQADgEADgFQABgEAAgGQAAgFgBgEQgDgFgDgEQgCgEgGgCQgEgDgGABQgFgBgFADg");
	this.shape_4.setTransform(-11.5,8.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AATA9IAAgqIgBgJQgBgFgCgDIgFgDQgDgCgFgBQgEAAgEACIgGAEQgGAHAAALIAAApIgPAAIAAh5IAPAAIAAA5QADgFAHgFIAHgDIAGgBQAIABAFACQAFADAEADQADAFACAEQACAGAAAGIAAAwg");
	this.shape_5.setTransform(-21,5.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgVA4QgKgFgGgIIAMgLQAEAGAHAEQAGAEAIAAIAHgCQAEAAAEgDQADgCACgEQACgDAAgGQAAgFgCgDQgCgEgEgCQgEgCgFgCIgJgDIgLgFQgFgBgEgDQgEgEgDgFQgCgFAAgJQAAgIADgGQAEgGAFgEQAGgEAHgCIANgBIAJAAIAJADQAJAEAFAFIgLALQgEgEgFgDQgGgEgHAAIgHABIgHAEIgFAGQgCADAAAFQAAAEABAEIAFAFIAIAEIAIADIAMAEQAFACAFADQAFADADAGQADAGAAAIQAAAJgDAHQgDAFgGAFQgFAFgHACQgIABgGAAQgLAAgKgDg");
	this.shape_6.setTransform(-30.4,6.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ordernow, new cjs.Rectangle(-36.9,-5.8,77.8,23.7), null);


(lib.nineteengrapes = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteentopright();
	this.instance.parent = this;
	this.instance.setTransform(-49,-49.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.nineteengrapes, new cjs.Rectangle(-49,-49.5,98,99), null);


(lib.nineteencheese_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteencheese();
	this.instance.parent = this;
	this.instance.setTransform(-99,-51);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.nineteencheese_1, new cjs.Rectangle(-99,-51,198,102), null);


(lib.nineteenbottomleft_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteenbottomleft();
	this.instance.parent = this;
	this.instance.setTransform(-62,-78);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.nineteenbottomleft_1, new cjs.Rectangle(-62,-78,124,156), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.kalelogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeAfQgNgMAAgTQAAgRANgNQAMgNASAAQASAAANANQANANAAARQAAATgNAMQgNANgSAAQgSAAgMgNgAgYgYQgJAKgBAOQABAQAJAKQAKAKAOAAQAPAAAKgKQAKgKAAgQQAAgOgKgKQgKgKgPAAQgOAAgKAKgAAMAZIgOgVIgFAAIAAAVIgJAAIAAgzIATAAQARAAAAAQQAAAMgMACIAPAVgAgHgDIAHAAQAMAAAAgHQAAgIgMAAIgHAAg");
	this.shape.setTransform(35,15.9,0.269,0.269);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjnEaQgVgDgHgEQgJgFAAgNQAAgKAGgGQAFgHAJAAIARAAQAKAAAFgMQACgKAAgXIAAl5QAAgXgCgKQgFgLgKAAIgRAAQgJAAgFgHQgGgHAAgKQAAgNAJgFQAHgEAVgDQBcgNBsAAQBOAAA1ASQA1ASAnAoQAlAlAVA5QATA4AABEQAABNgZA9QgZA+gwAlQgkAegxAOQgwAOhFAAQh4AAhQgNgAgwjrQgcAFgJALQgKAMAAAhIAAFjQAAAhAUALQAOAHAnADQBNAEArhAQArg/AAhwQAAhwgqg/Qgrg/hKAAIgeADg");
	this.shape_1.setTransform(16.7,8.1,0.269,0.269);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNBlQgFgCAAgIIAAiTQAAgKgLAAIgzAAQgKAAAAgOQAAgWAKAAICfAAQAMAAAAASQAAASgLAAIgyAAQgLAAAAAKIAACTQAAAHgFADQgEACgKAAQgJAAgEgCg");
	this.shape_2.setTransform(21.8,23.7,0.269,0.269);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhMBmQgNAAAAgPIAAiuQAAgOANAAICbAAQAGAAADAFQACADAAAJQAAASgMAAIh5AAQgIAAAAAJIAAAcQAAAKAKgBIBFAAQALABAAARQAAARgKAAIhFAAQgLAAAAAKIAAAfQAAAKAKAAIB3AAQALAAAAATQAAARgKAAg");
	this.shape_3.setTransform(14,23.7,0.269,0.269);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA5BlQgEgBgEgFIhAhGQgKgIgUAAQgFAAgEAEQgEAFAAAGIAAA7QAAAIgGACQgEACgKAAQgRAAAAgMIAAi0QAAgIAFgDQAEgCALAAQARAAAAAMIAAA3QAAANAKAAQALAAAFgCQAEgBAFgFIBJhDQAMgLANALQALAMgJAJIhAA7QgJAHAIAKIBPBVQAIAJgGAFQgFAEgNAAQgMAAgGgCg");
	this.shape_4.setTransform(6.1,23.7,0.269,0.269);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAuBeIgggxQgFgKgKAAIgtAAQgEAAgDADQgDAEgBAEIABAxQAAAGgKABIgPABQgMAAAAgMIAAi5QgBgIAKAAIBqAAQAgAAAUATQAVATAAAfQAAAYgPAPQgIAJgPAKQgHAGADAGIAjAyQAFAIgFAEQgEAEgPAAQgRAAgGgJgAg5g4IAAAuQABAFAEAEQAEABAFAAIA+AAQAQAAALgHQALgJAAgRQAAgQgLgIQgLgJgQAAIg+AAQgOAAAAAKg");
	this.shape_5.setTransform(-3,23.7,0.269,0.269);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABCBfIgOgbQgDgGgGAAIhTAAQgJAAgEAMIgMAVQgDAIgSAAQgXAAAGgMIBZi4QAFgKAKABQAMAAADAIIBYC6QADAHgJADQgGABgIAAQgPABgDgJgAgEgdIgYAyQgCADABACQACADAEAAIAwAAQADAAACgCQACgCgCgDIgZgzQgCgEgDABQgCAAgCADg");
	this.shape_6.setTransform(-11.9,23.7,0.269,0.269);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABZBkQgFgDAAgEIgPhsQgBgGgFAAQgDAAgDAEIgxA9QgEAGgFAAQgHAAgEgGIgtg8QgCgDgEAAQgFAAgBAIIgOBnQgCALgTAAQgGAAgFgDQgGgDAAgFIAViwQACgKADgDQAEgEALAAQAJAAAGAJIA4BOQAFAIAEAAQAFAAAGgIIA7hQQAFgIAKAAQAGAAADADQAEACACAIIAVC1QABALgXAAQgFAAgFgDg");
	this.shape_7.setTransform(-21,23.7,0.269,0.269);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AipF/QhPhTAAiLQAAhZAghEQAfhCA7gnQAZgTAmgTQAngTAmgOQAKgDgDgJQgCgKgOADQg5ALgsgRQgXgJgdgSQgggUgKgEQgtgWg7AZQgVAJgMgLQgLgLAGgXQAXhWBDg3QBKg9BQAXQA0APAlA0QAmA2AfALQATAGgBAPQAAAOgRADQgaAFgjgQQgfgPgegbQgggdgugCQgsgCgbAVQgLAJADAGQADAHALgCQBPgRAxA3QAkAoAuAPQA4ASAugeIAZgXQANgMAMADQAPAEgBAUQgBAUgTAZQgiAsg+AeQhEAjgfAeQgwAvgTA9QgPAzAABRQAABxAqBAQAqBABKAAQBJAAArhCQArhBAAhwQAAhfgYg4QgZg6g1gUQgbgLAFgTQAFgUAhgDQA3gHA8AtQBoBMAACkQAACOhPBVQhQBUiHAAQiDAAhPhUg");
	this.shape_8.setTransform(3.9,-14.6,0.269,0.269);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABnDwQhFg1gYheIgBgCQgCgLgHgBQgGAAgCALIgBACQgYBfhHA2QhGA2hpAAQh+AAhMhQQhLhQgBiFQAAiHBMhRQBLhQCAAAQBpAABIA3QBGA2AXBgQACALAGAAQAHgBACgLIABAAQAXhgBGg1QBHg3BoAAQB/AABMBQQBNBPAACFQAACHhNBRQhMBRiBAAQhmAAhHg3gACmiqQgoA/AABuQAABsAoA+QApA9BIAAQBFAAApg/QApg/ABhrQAAhsgqg+QgqhAhGAAQhGAAgpA/gAmFiqQgpA/AABuQAABrApA/QApA9BHAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhGAAQhGAAgpA/g");
	this.shape_9.setTransform(-5.6,8.1,0.269,0.269);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ai5EbQgWAAgJgFQgIgFAAgOQAAgKAGgHQAHgHAJAAIARAAQAKAAAEgLQADgKAAgXIAAl7QAAgZgDgIQgCgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFvAAQANAAAHAFQAIAFACALIAMA7QAEAQgGAJQgFAJgLAAQgPAAgHgOIgJgSQgFgPgPgFQgNgEggAAIhtAAQghAAgJAIQgIAJAAAiIAABlQAAAZAIAFQAFAEAdAAIBFAAQAbAAAIgEQAHgDACgNIAAgFQAEgVATAAQAOAAAFAIQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgTAAgEgWIgBgGQgCgNgHgDQgHgEgbAAIhFAAQgdAAgFAEQgIAFAAAZIAACLQAAAbACAGQAGALAMAAIATAAQAKAAAGAHQAGAHAAAKQAAAOgJAFQgIAFgYAAg");
	this.shape_10.setTransform(-26.4,8.1,0.269,0.269);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhTEcIgSgFQgKAAgIAIQgLAIgKAAQgKABgGgHQgFgGgEgQIgWhUQgCgIAAgJQAAgMAIgHQAHgIAMAAQAMAAAJALIAMARQAWAfAiASQAhASAlAAQAoAAAZgVQAbgVAAgiQAAgggcgfQgYgbhBguIhOg2QgRgPgUgWQggglAAg0QAAg9ArgmQArglBGAAQAmgBAjAIIAVAFQAHACAFAAQAHAAAMgIQAJgHAJABQATAAAFAXIAUBcQABAEABAIQAAAIgIAGQgHAGgKAAQgMAAgKgPQgOgVgHgHQgGgHgOgLQgigbguAAQgcAAgSAQQgRAQAAAaQAAAWAJANQANASAaAVIApAdQAzAkAWARQAXASAUAUQAWAWAMAeQAMAfAAAgQAABKgyAtQgzAshUAAQgyAAgmgLg");
	this.shape_11.setTransform(29.5,8.1,0.269,0.269);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ah9EYQgLgKgIgWIhIjYQgBgGgEAAQgFAAgBAFIhODZIgJAVQgDAHgFAEQgMAKgRgBQgSABgLgKQgKgIgJgYIinm+QgJgagHgIQgIgHgUgEQgNgCgFgGQgGgFABgLQAAgVAcAAICvAAQAdAAAAAWQgBAMgGAEQgIAGgQABQgPABgFAFQgHAFAAAKQAAAIAEALIBzFGQACAGAEgBQAEAAADgGIA/i2QAHgagGgVIgfhbIgHgUQgEgJgGgFQgGgEgQgEQgNgDgFgFQgGgFABgJQAAgaAdAAICmAAQAdAAABAWQAAAUgcAEQgRACgGAEQgGAFAAAMQAAAIAJAbIBfEsQACAGAEgBQAEgBACgEIBdk6QADgNAAgHQAAgTgcgEQgbgCAAgVQgBgNAIgGQAIgFAQAAIEmAAQAVAAAIAFQAIAFAAAOQAAAKgGAIQgGAGgJAAIgQAAQgLAAgGALQgBAIAAAZIAABuQAAAdAFAGQAFAHAYAAIB0AAQAXAAAHgIQADgDAAgHIAAgdIAAhpQAAgbgCgGQgFgLgLAAIgPAAQgKAAgHgGQgGgIgBgKQABgOAIgFQAJgFAVAAICaAAQAXAAAIAFQAJAFAAAOQgBAKgGAIQgHAGgJAAIgRAAQgEAAgEAEQgFADgBAEQgDAHAAAaIAAF9QAAAZADAIQAEAKAKAAIARAAQAKABAGAGQAHAIAAAJQgBAPgHAEQgJAGgXAAIiaAAQgVAAgJgGQgIgEAAgPQABgJAGgIQAHgGAJgBIAPAAQALAAAFgKQACgGAAgbIAAh8IAAgeQAAgGgDgFQgHgHgXAAIh0AAQgYAAgFAGQgFAIAAAcIAACCQAAAYABAJQAGAKALAAIAQAAQAJABAGAGQAFAIAAAKQABANgJAGQgHAFgVAAIibAAQgVAAgJgGQgJgFAAgOQAAgJAHgIQAGgGAKgBIAQAAQAFAAAEgCQAFgDAAgFQAEgGAAgbIAAl9QAAgxgkAFQgMACgGAIQgIAJgHAXIiGGyQgKAfgKAMQgKALgTgBQgTAAgLgJg");
	this.shape_12.setTransform(-20.1,-9.9,0.269,0.269);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AihEbQgVAAgIgFQgJgFAAgOQAAgKAHgGQAGgHAJAAIAQAAQAEAAAEgDQAFgDABgFQADgHAAgZIAAl+QAAgZgDgJQgDgLgLABIgQAAQgKgBgHgGQgHgHAAgKQAAgOAJgGQAJgFAWAAICdAAQAWAAAJAFQAJAGAAAOQAAAKgHAHQgHAGgJABIgRAAQgOgBgEALQgDAHAAAbIAAFjQAAAcADAKQACAJAHAFQAHAEAKACQAMABAaAAIAwAAQAvAAAPgfIAHgPQAIgQAPgBQAMABAFAIQAFAJgDAQIgNBCQgFAVgaAAg");
	this.shape_13.setTransform(18.6,-10,0.269,0.269);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AjREWQgJgGAAgOQAAgJAHgHQAGgGAJAAIARAAQAEAAAEgDQAEgEABgEQAEgKAAgYIAAl7QAAgXgEgKQgBgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFSAAQAZAAAFAVIAMA7QADAQgFAJQgFAJgMAAQgOAAgIgOQgDgFgFgNQgGgQgPgFQgMgEggAAIhQAAQghAAgJAJQgIAJAAAiIAABkQAAAaAHAFQAFADAeAAIAmAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgTAAgEgWIgBgGQgCgNgHgDQgHgEgbAAIgmAAQgeAAgFAEQgHAFAAAZIAABsQAAAiADALQADALAKAEQAQAGAhAAIBVgBQAvAAAPgfIAHgQQAIgQAPAAQAMAAAFAJQAFAJgDAQIgNBCQgFAVgaAAIlhAAQgWAAgIgFg");
	this.shape_14.setTransform(30.7,-10,0.269,0.269);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0C6E47").s().p("AqoZMQk6iFjyjyQjyjxiFk7QiKlFAAlkQAAljCKlFQCFk6DyjzQDyjxE6iFQFFiKFjAAQFkAAFFCKQE6CFDyDxQDyDyCFE7QCKFFAAFjQAAFkiKFFQiFE7jyDxQjyDyk6CFQlFCKlkAAQljAAlFiKg");
	this.shape_15.setTransform(0,0,0.269,0.269);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.kalelogo, new cjs.Rectangle(-47,-47,94,94), null);


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("EgYcgkyMAw5AAAMAAABJlMgw5AAAg");
	this.shape.setTransform(0,0,1.019,1.017);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-160.5,-240.5,321,481), null);


(lib.fourteentable = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.seventeentable();
	this.instance.parent = this;
	this.instance.setTransform(-160,-240);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteentable, new cjs.Rectangle(-160,-240,320,480), null);


(lib.crowdpleasing = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgNBiIgUgEIgGAEIgGABIgEgBIgEgCQgGgGgFgPQgGgPAAgOQAAgGAEgEQADgEAFAAQAIAAAJAPIAHAMQAGAHAKAEQAJAFALAAQAMAAAHgHQAIgGAAgKQAAgQgfgPIgLgGQgdgOgLgMQgKgMAAgSQAAgYARgQQARgPAbAAIANABIANACIAJgEIAGgBQAJAAAJAPQAJAPAAAQQAAAHgDAEQgDADgGAAQgEAAgEgDQgEgEgGgJQgHgLgIgFQgHgFgLAAQgKAAgGAGQgHAHAAAKQAAAIAHAHQAHAGAWAMIACABQA1AZAAAfQAAAagUARQgVASgeAAg");
	this.shape.setTransform(124.2,26.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("Ag4BdQgJgDAAgIQAAgHAJgCIAFgDQAFgCACgHQACgGAAgPIgBgMIAAgQIAAgLQAAghgBgLQgCgKgEgCIgIgEQgMgDAAgHQAAgEAEgEQADgDAJgDIAZgIIARgEQAJAAADAaIAAAEIABABQAKgPAKgJQALgHAKgBQANABAIAHQAIAJAAAMQAAAOgGAHQgGAIgLAAIgJgCIgIgGIgEgHQgCgFgCAAQgNAAgFASQgFASAAA4QAAAQACAJQACAIAFADIAHACQAMAEAAAHQAAAHgLADQgKAEgZAAQgdAAgJgEg");
	this.shape_1.setTransform(109.4,26.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("Ag8BHQgbgcAAgoQgBgrAcgcQAbgdArAAQAkAAAVAVQAWAVgBAiQAAAMgDAEQgEAEgOgBIhHAAQgHAAgDgCQgDgEAAgFQAAgEADgDQADgDAHAAIAmAAIAKgBQACgCABgEQAAgSgNgMQgMgNgRAAQgWAAgLAUQgLAUAAAbQAAAcAPAWQAPAVAXAAQAOAAAKgDQAJgDAJgHIAHgEQAKgJAEABQAFgBACADQADADAAAEQAAAEgEAHQgFAGgIAHQgQANgPAHQgQAFgSAAQgnAAgagbg");
	this.shape_2.setTransform(91.9,26.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("AgJBxQgKgDgGgGQgHgGgDgLQgCgKAAgcIAAhkIgSAAIgFgBIgCgGIAAgEQAAgGAUgRIAIgHIAHgGQATgRAIAAIAFACQAAAAABAAQAAABAAAAQABABAAABQAAAAAAABIAAAjIAqAAQAEAAACACQACACAAAFIAAAFQAAAEgCADQgCACgEAAIgnAAIgDABIgBAFIAABdQAAAXAEAHQAEAGALAAQAGAAAJgDIANgDQAEAAADADQADACAAADQAAALgQAJQgQAKgUAAQgLAAgJgDg");
	this.shape_3.setTransform(75.4,24.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AgJBxQgKgDgGgGQgHgGgDgLQgCgKAAgcIAAhkIgSAAIgFgBIgCgGIAAgEQAAgGAUgRIAIgHIAHgGQATgRAIAAIAFACQAAAAABAAQAAABAAAAQABABAAABQAAAAAAABIAAAjIAqAAQAEAAACACQACACAAAFIAAAFQAAAEgCADQgCACgEAAIgnAAIgDABIgBAFIAABdQAAAXAEAHQAEAGALAAQAGAAAJgDIANgDQAEAAADADQADACAAADQAAALgQAJQgQAKgUAAQgLAAgJgDg");
	this.shape_4.setTransform(62,24.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AAhBZIgKgKIgIAEQgXAPgXAAQgbAAgRgQQgRgQAAgZQAAgfAWgPQAWgRAnAAQAJAAAEACQAFADABAHQAAALgOAAQgRAAgMAJQgMAJAAAQQAAAPALAJQAJAJARAAQARAAAIgIQAIgJAAgTIAAhHQAAgRgHgJQgIgJgMAAQgJAAgIAFQgIAEgHAIIgEAFQgMAOgNAAQgHAAgEgEQgFgFABgIQAAgSAVgMQAWgMAiAAQAVAAAOAFQAPAGAJAKQAFAIADALQACAMAAAbIAAA7QAAALABAFQADAFAEABIAFACQAMADAAAHQAAAJgNAHQgNAHgQAAQgIAAgKgJg");
	this.shape_5.setTransform(45.5,26.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AgfCHQgJgDAAgIQAAgGAIgEIAJgFQADgDACgLIABgmIAAgdIAAgjIAAgOQAAgvgCgOQgCgOgEgCIgLgEQgMgDAAgHQAAgFAEgDQADgDAOgFIAZgHIATgCQAFAAADADQACAEAAAJIgBAOQgCBDAABDIACBAQABAOADAEIAKAFQAJAEAAAHQAAAHgJADQgKADgYAAQgcAAgJgDg");
	this.shape_6.setTransform(29.6,22.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AhhCFQgKgDAAgIQgBgIAMgEIAIgFQAFgDACgWQABgWAAg7IgBhHQgCgbgDgEQgBgCgKgEQgLgFABgHQAAgGAFgEQAGgDAMAAIAUAAIAVAAIAmgBIAegBQAqAAAVASQAVASAAAkQAAAngbAVQgZAUgyAAQgSAAgBgNQAAgMAQAAQAYAAAPgNQAOgMAAgcQAAgagPgMQgOgMgfAAQgOAAgFACQgFACgDAFIgCARIgBAnIAABTIACA1QACAOADADIAIAEQAMAEAAAIQAAAIgKADQgLAEgeAAQgdAAgLgEg");
	this.shape_7.setTransform(13.8,22.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("Ag9BHQgbgcAAgoQAAgrAcgcQAcgdApAAQAlAAAWAVQAUAVAAAiQAAAMgDAEQgDAEgOgBIhIAAQgGAAgDgCQgEgEAAgFQAAgEAEgDQADgDAGAAIAmAAIAKgBQACgCAAgEQAAgSgMgMQgMgNgRAAQgWAAgLAUQgLAUAAAbQAAAcAPAWQAPAVAXAAQAOAAAJgDQAKgDAJgHIAHgEQAJgJAGABQAEgBADADQADADAAAEQAAAEgGAHQgEAGgIAHQgQANgQAHQgPAFgRAAQgoAAgbgbg");
	this.shape_8.setTransform(-18.3,26.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E46").s().p("AgNBiIgUgEIgGAEIgGABIgEgBIgEgCQgGgGgFgPQgGgPAAgOQAAgGAEgEQADgEAFAAQAIAAAJAPIAHAMQAGAHAKAEQAJAFALAAQAMAAAHgHQAIgGAAgKQAAgQgfgPIgLgGQgdgOgLgMQgKgMAAgSQAAgYARgQQARgPAbAAIANABIANACIAJgEIAGgBQAJAAAJAPQAJAPAAAQQAAAHgDAEQgDADgGAAQgEAAgEgDQgEgEgGgJQgHgLgIgFQgHgFgLAAQgKAAgGAGQgHAHAAAKQAAAIAHAHQAHAGAWAMIACABQA1AZAAAfQAAAagUARQgVASgeAAg");
	this.shape_9.setTransform(-36.5,26.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E46").s().p("Ag9BHQgbgcAAgoQABgrAbgcQAcgdApAAQAlAAAWAVQAUAVABAiQgBAMgDAEQgDAEgOgBIhIAAQgGAAgEgCQgDgEAAgFQAAgEADgDQAEgDAGAAIAnAAIAJgBQADgCgBgEQAAgSgMgMQgMgNgRAAQgWAAgLAUQgLAUAAAbQAAAcAPAWQAPAVAXAAQAOAAAJgDQAKgDAJgHIAHgEQAJgJAGABQAEgBACADQAEADAAAEQAAAEgGAHQgEAGgIAHQgRANgPAHQgPAFgRAAQgoAAgbgbg");
	this.shape_10.setTransform(-54.4,26.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E46").s().p("Ag8BHQgbgcAAgoQAAgrAbgcQAbgdArAAQAkAAAVAVQAWAVgBAiQABAMgEAEQgEAEgOgBIhHAAQgGAAgDgCQgEgEAAgFQAAgEAEgDQADgDAGAAIAmAAIAKgBQADgCAAgEQAAgSgNgMQgMgNgRAAQgWAAgLAUQgLAUAAAbQAAAcAPAWQAPAVAXAAQAOAAAKgDQAJgDAJgHIAHgEQAKgJAEABQAFgBADADQACADAAAEQAAAEgEAHQgFAGgIAHQgQANgPAHQgQAFgSAAQgnAAgagbg");
	this.shape_11.setTransform(-74.2,26.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E46").s().p("AAaCHQgKgDAAgHQAAgIAKgDIAIgDQADgDADgIQABgIAAgTQAAg9gHgPQgIgPgUABQgJAAgJAFQgJAGgFAJQgFAJgBAOQgCAPAAAkQAAAUACAFQACAGADADIAIADQAJADAAAIQAAAHgJADQgJADgZAAQgdAAgJgDQgJgDAAgIQAAgHAJgDIAFgDQAFgDACgHQACgIAAgUIAAggIAAgcIgBhUQgBgWgDgDQgCgDgMgDQgKgDgBgHQABgEAEgFQAFgDAQgGIATgFIARgCQAHAAACAEQADADAAAIIAAAIIgCBLIAAAJIABAFIADABIAEgEIAHgHQAJgJALgGQAJgEANAAQAgAAAQAVQAPAVAAApIABASIAAAiIAAAKQAAAKACAEQABAEAFACIAEACQAJAEAAAHQABAIgKADQgJADgdAAQgZAAgJgDg");
	this.shape_12.setTransform(-95.7,22.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E46").s().p("AgcCDQgagJgSgRQgXgUgLgcQgLgcAAggQAAgaAHgXQAIgXAPgSQATgWAagMQAagMAfAAIAWABIAlAIIAEgBIAOgDIAHACIAFAFQAGAKAEAPQADAOAAALQAAAIgCAEQgDAEgGAAQgIAAgPgRIgLgNQgLgLgPgFQgPgGgSAAQgjAAgWAZQgVAZAAAsQAAA3AbAkQAbAkAoAAQARAAAPgGQAOgFAJgJIAJgLQAJgLAGAAQAEAAAEAFQADAFgBAJQAAARgEALQgFAKgJAAIgBAAIgDgBQgRAJgSAFQgSAEgTAAQgbAAgZgJg");
	this.shape_13.setTransform(-119.3,22.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E46").s().p("AhFB7QgYgPAAgVQAAgJAFgGQAFgGAKAAQAJAAAEAEQAEAFACAIQAFAOAMAIQAMAIAWAAQAZAAARgKQAQgJAAgPQAAgJgGgEQgGgFgMAAIgVABIgdACQgiAAgRgMQgTgLABgPQgBgKAHgJQAGgIAOgIQgLgKgFgMQgGgMAAgOQAAgfAXgUQAXgVAjAAIATACIAeAGQAGAAAJgEQAIgDALgIIAHAFIACAHQAAAIgGAHQgGAIgLAFIAGAQIACAPQgBAfgWAUQgXASgkAAIgUgBIgSgEIgFAHIgDAHQAAAJAJAEQAJAFATAAIAcgCIAdgDQAaAAAOALQAOALAAAUQAAAegdAUQgeATgtAAQgjAAgYgOgAgehdQgKAMAAATQAAATAKAMQAJAMAQAAQAOAAALgMQALgMAAgTQAAgTgKgMQgLgMgPAAQgPAAgKAMg");
	this.shape_14.setTransform(125.6,-14.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E46").s().p("AhbBdQgKgDAAgIQAAgHAKgDIAEgCQAFgDACgGQACgGAAgOIAAgNIgBgPIAAgTQAAgdgBgKQgBgIgEgDIgJgDQgMgDAAgGQAAgFAFgDQADgDAIgEIAbgJIATgCQAGAAACACQACADAAAGIAAAMIABADIABAAIABAAIABAAIAEgFIAEgDQAVgUAXABQANAAAMAFQANAHAJAJQAIALAEAOQAEAOAAAfIAAAYIAAANIgBAKQAAANACAGQACAFAEADIAGACQAJADgBAHQAAAIgIADQgJADgcAAQgbAAgJgDQgJgCAAgIQAAgHAJgEIAIgDQAEgCACgIQACgIAAgVQAAg7gIgPQgIgPgTAAQgJAAgKAGQgJAGgFAKQgEAIgCAPQgCAOAAAlQAAASACAGQACAGAEACIAHADQAKAEAAAHQAAAHgKAEQgJACgZAAQgcAAgJgDg");
	this.shape_15.setTransform(103.7,-18.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E46").s().p("AggCGQgKgDAAgIQAAgHAKgDIAEgCQAFgDACgGQACgGAAgOIAAgNIgBgPIAAgUQAAgdgBgJQgBgIgEgDIgJgDQgMgDAAgGQABgFADgDQAEgDAIgEIAdgJIASgDQAFAAADADQACAEAAAIIAAAMIgBAIIgBAvIAAABIAAAuQgBASACAIQACAHAEACIAHADQAKAEAAAHQAAAHgKAEQgJACgYAAQgdAAgIgDgAgWheQgJgHABgKQgBgKAKgIQAIgIANAAQAMABAHAGQAIAHAAAKQAAALgJAHQgIAHgMABQgNgBgHgGg");
	this.shape_16.setTransform(87.1,-22.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E46").s().p("AgNBiIgUgEIgGAEIgGABIgEgBIgEgCQgGgGgFgPQgGgPAAgOQAAgGAEgEQADgEAFAAQAIAAAJAPIAHAMQAGAHAKAEQAJAFALAAQAMAAAHgHQAIgGAAgKQAAgQgfgPIgLgGQgdgOgLgMQgKgMAAgSQAAgYARgQQARgPAbAAIANABIANACIAJgEIAGgBQAJAAAJAPQAJAPAAAQQAAAHgDAEQgDADgGAAQgEAAgEgDQgEgEgGgJQgHgLgIgFQgHgFgLAAQgKAAgGAGQgHAHAAAKQAAAIAHAHQAHAGAWAMIACABQA1AZAAAfQAAAagUARQgVASgeAAg");
	this.shape_17.setTransform(73.6,-18.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006E46").s().p("AAhBZIgKgKIgIAEQgXAPgXAAQgbAAgRgQQgRgQAAgZQAAgfAWgPQAWgRAnAAQAJAAAFACQAEADABAHQAAALgOAAQgRAAgMAJQgMAJAAAQQAAAPALAJQAJAJARAAQARAAAIgIQAIgJAAgTIAAhHQAAgRgHgJQgIgJgMAAQgJAAgIAFQgIAEgHAIIgEAFQgMAOgNAAQgHAAgEgEQgFgFABgIQAAgSAVgMQAWgMAiAAQAVAAAOAFQAPAGAJAKQAFAIADALQACAMAAAbIAAA7QAAALABAFQADAFAEABIAFACQAMADAAAHQAAAJgNAHQgNAHgQAAQgIAAgKgJg");
	this.shape_18.setTransform(55.8,-18);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006E46").s().p("Ag9BHQgbgcAAgoQABgrAbgdQAcgcApAAQAlAAAWAVQAUAUABAkQgBALgDAEQgDAEgOAAIhIAAQgGAAgEgEQgDgCAAgGQAAgFADgCQAEgDAGAAIAnAAIAJgCQADgBgBgEQAAgSgMgNQgMgMgRAAQgWAAgLAUQgLAUAAAaQAAAeAPAVQAPAVAXAAQAOAAAJgDQAKgDAJgGIAHgGQAJgHAGgBQAEAAACAEQAEACAAAEQAAAFgGAGQgEAHgIAGQgRAOgPAFQgPAGgRAAQgoAAgbgbg");
	this.shape_19.setTransform(35.6,-18);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#006E46").s().p("AgfCHQgJgDAAgIQAAgGAIgEIAJgFQADgDACgLIABgmIAAgdIAAgjIAAgOQAAgvgCgOQgCgOgEgCIgLgEQgMgDAAgHQAAgFAEgDQADgDAOgFIAZgHIATgCQAFAAADADQACAEAAAJIgBAOQgCBDAABDIACBAQABAOADAEIAKAFQAJAEAAAHQAAAHgJADQgKADgYAAQgcAAgJgDg");
	this.shape_20.setTransform(20.1,-22.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#006E46").s().p("AhhCFQgLgDAAgIQABgIAMgEIAHgFQAFgDABgWQACgWAAg7IgChHQgBgbgCgEQgCgCgLgEQgJgFgBgHQAAgGAHgEQAFgDAMAAIATAAIAWAAIAmgBIAdgBQAqAAAWASQAUASAAAkQAAAngaAVQgZAUgyAAQgTAAABgNQAAgMAQAAQAXAAAPgNQAOgMAAgcQAAgagPgMQgPgMgdAAQgOAAgGACQgFACgCAFIgCARIgBAnIAABTIABA1QABAOADADIAJAEQAMAEgBAIQAAAIgKADQgKAEgeAAQgdAAgLgEg");
	this.shape_21.setTransform(4.3,-22.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#006E46").s().p("AglAUQgFAAgCgCQgDgDAAgFIABgIIAFgLIAFgHQACgBAJAAIAJAAIAQAAIAggBIAFAAQAGAAADACQACABAAAGQAAAJgGAKQgGAIgIABIgJgBIgKAAIgqACIgEAAg");
	this.shape_22.setTransform(-13.8,-18.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#006E46").s().p("AhSByQgWgZAAgpQAAguAagcQAZgdAoAAIANABQAGADADAEQADAEAAAFQAAAKgMgBIgFAAIgFAAQgVAAgMARQgNAQAAAdQAAAgAOAUQANAUAWAAQATAAAKgLQALgLAAgVIAAg0IAAhVQAAgOgCgEQgDgFgHgDIgFgBQgLgEAAgGQAAgGAEgDQAFgEAOgFIAVgGIASgCQAGAAADADQADAEAAAJIgBAJIgCBzIACBPQABASADADIANADQAKADAAAGQAAAKgbAIIgTAFIgOACQgGAAgCgEQgCgCAAgHIAAgJIgBgDIgBgBIgGADIgIAHQgLAIgKAEQgLAEgLAAQgkAAgWgZg");
	this.shape_23.setTransform(-30.8,-22.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#006E46").s().p("AALAVIgWg7QgLgbgJgEIgFgDQgLgEAAgHQAAgHAJgDQAKgDAdAAQAaAAAJADQAJADAAAHIgBAGIgEAEIgGACQgIAEAAADIAEANIAPAnIAQAkQAFAJACAAQADAAADgGIAIgQIAVgvQAHgSAAgHIgCgGIgEgFIgGgCQgIgDAAgGQAAgHAIgDQAJgDAXAAQAUAAAIADQAIADAAAHQAAAHgKADIgGADQgJAEgRAnIgEAKIgIARQgrBhgMAAQgNAAghhMgAhuAKIgFgLIgNggQgMgggIgEIgGgDQgLgEAAgHQAAgHAKgDQAJgDAfAAQAZAAAJADQAJADAAAHIgBAHIgDADIgGACQgIAEAAADIAEARIAOAjIAQAjQAFAKACAAQAGAAAFgMIAHgOIAEgFQACgCAEAAQAFAAADADQACADAAAEQAAAFgFAKQgUArgIAPQgJAOgHAAQgNAAglhXg");
	this.shape_24.setTransform(-57.8,-17.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#006E46").s().p("AhEBHQgbgcAAgqQAAgqAcgcQAcgcAqAAQAoAAAaAaQAaAbAAApQAAAqgcAeQgcAdgoAAQgoAAgbgbgAgjg3QgMAPAAAZQAAAkAQAaQAQAZAVAAQATAAAMgQQALgPAAgZQAAgkgQgZQgQgagVAAQgTAAgLAQg");
	this.shape_25.setTransform(-84,-18);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#006E46").s().p("Ag4BdQgJgDAAgIQAAgGAJgEIAFgCQAFgDACgGQACgGAAgOIgBgNIAAgPIAAgMQAAghgBgLQgCgKgEgDIgIgDQgMgDAAgGQAAgFAEgDQADgEAJgDIAZgIIARgDQAJAAADAZIAAAEIABAAQAKgOAKgJQALgHAKAAQANAAAIAHQAIAJAAANQAAANgGAHQgGAHgLABIgJgCIgIgGIgEgHQgCgFgCAAQgNAAgFASQgFASAAA4QAAARACAIQACAIAFACIAHADQAMADAAAIQAAAHgLADQgKADgZAAQgdAAgJgDg");
	this.shape_26.setTransform(-101.4,-18.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#006E46").s().p("AgdCDQgYgJgUgRQgWgUgLgcQgMgcAAggQABgaAHgXQAIgXAPgSQASgWAbgMQAagMAfAAIAWABIAlAIIAEgBIAPgDIAGACIAFAFQAGAKAEAPQAEAOgBALQAAAIgDAEQgCAEgGAAQgIAAgOgRIgNgNQgJgLgQgFQgPgGgRAAQglAAgVAZQgVAZAAAsQAAA3AbAkQAbAkAoAAQARAAAOgGQAPgFAKgJIAJgLQAIgLAFAAQAFAAAEAFQACAFAAAJQABARgFALQgFAKgJAAIgCAAIgCgBQgRAJgSAFQgSAEgTAAQgbAAgagJg");
	this.shape_27.setTransform(-121.7,-22.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.crowdpleasing, new cjs.Rectangle(-136.8,-46.7,273.7,93.4), null);


(lib.bottomright = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteentomatoes();
	this.instance.parent = this;
	this.instance.setTransform(-91.5,-100.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bottomright, new cjs.Rectangle(-91.5,-100.5,183,201), null);


(lib.seventeenrollover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(12).call(this.frame_23).wait(7));

	// rectangle
	this.instance = new lib.seventeenvideo();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-73.7,-14.2,147.5,38.4);


(lib.fourteentableuse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.fourteentable();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.fourteentableuse, new cjs.Rectangle(-160,-240,320,480), null);


// stage content:
(lib.interstitialnineteen = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_40 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_226 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(40).call(this.frame_40).wait(186).call(this.frame_226).wait(4));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(160.4,240.1,1.553,0.731,0,0,0,0.2,0.1);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(230));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(160,240);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(230));

	// white-fade
	this.instance_1 = new lib.whiterectanglefadeone();
	this.instance_1.parent = this;
	this.instance_1.setTransform(161.5,239);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:0},9).wait(221));

	// kale-logo
	this.instance_2 = new lib.kalelogo();
	this.instance_2.parent = this;
	this.instance_2.setTransform(160.1,37);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({scaleX:0.09,scaleY:0.09},0).to({scaleX:1.08,scaleY:1.08,alpha:1},6,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},7,cjs.Ease.get(1)).wait(208));

	// get-party-started
	this.instance_3 = new lib.partystarted();
	this.instance_3.parent = this;
	this.instance_3.setTransform(160,122.8);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(203).to({alpha:1},10).wait(17));

	// HOLIDAY-BITES-PLATTERS
	this.instance_4 = new lib.smallbites();
	this.instance_4.parent = this;
	this.instance_4.setTransform(160,201.8);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(203).to({alpha:1},10).wait(17));

	// ready-to-serve
	this.instance_5 = new lib.readytoserveshrimp();
	this.instance_5.parent = this;
	this.instance_5.setTransform(160,183.5);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(140).to({alpha:1},10).wait(40).to({alpha:0},5).wait(35));

	// party-perfect 
	this.instance_6 = new lib.partyperfect();
	this.instance_6.parent = this;
	this.instance_6.setTransform(160,183.5);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(90).to({alpha:1},10).wait(40).to({alpha:0},5).wait(85));

	// crowd-pleasing
	this.instance_7 = new lib.crowdpleasing();
	this.instance_7.parent = this;
	this.instance_7.setTransform(160,183.5);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(40).to({alpha:1},10).wait(40).to({alpha:0},5).wait(135));

	// order-now
	this.instance_8 = new lib.ordernow();
	this.instance_8.parent = this;
	this.instance_8.setTransform(157,293.1);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(53).to({y:291.6},0).to({alpha:1},10).wait(167));

	// cta-rollover
	this.cta_rollover = new lib.seventeenrollover();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(160,294);
	this.cta_rollover.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(53).to({alpha:1},10).wait(167));

	// cta-rectangle
	this.instance_9 = new lib.seventeenrectangle();
	this.instance_9.parent = this;
	this.instance_9.setTransform(160,294);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(53).to({alpha:1},10).wait(167));

	// cheese
	this.instance_10 = new lib.nineteencheese_1();
	this.instance_10.parent = this;
	this.instance_10.setTransform(99,51);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(9).to({alpha:1},10).wait(211));

	// bottom-right
	this.instance_11 = new lib.bottomright();
	this.instance_11.parent = this;
	this.instance_11.setTransform(228.5,379.5);
	this.instance_11.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(16).to({alpha:1},10).wait(204));

	// bottom-left
	this.instance_12 = new lib.nineteenbottomleft_1();
	this.instance_12.parent = this;
	this.instance_12.setTransform(62,402);
	this.instance_12.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(23).to({alpha:1},10).wait(197));

	// top-right
	this.instance_13 = new lib.nineteengrapes();
	this.instance_13.parent = this;
	this.instance_13.setTransform(271,49.5);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(30).to({alpha:1},10).wait(190));

	// table
	this.instance_14 = new lib.fourteentableuse();
	this.instance_14.parent = this;
	this.instance_14.setTransform(160,240);

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(230));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(154.1,230,335,496);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 320,
	height: 480,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/nineteencheese.png", id:"nineteencheese"},
		{src:"images/index_atlas_NP_.jpg", id:"index_atlas_NP_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;